### ISSUE TITLE
Add proper Documentation

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#10]
- [x] API Docs

- [x] Readme

- [ ] User Guide

- [x] Getting Started

**Comment by shreyasbapat** [comment]
Added Readme in https://github.com/einsteinpy/einsteinpy/commit/241311db2291b5b5fc35d5bd496ed1d16fee5344

**Comment by shreyasbapat** [comment]
Added documentation in #34  at https://einsteinpy-project.readthedocs.io/en/latest/

**Comment by shreyasbapat** [comment]
Added API docs in #72

**Comment by shreyasbapat** [comment]
This issue is just one User Guide push close.

**Comment by ritzvik** [comment]
Great efforts @shreyasbapat 
Some subtle issues to be fixed:

Metric module contains Schwarzschild module not Geodesics module.
![1](https://user-images.githubusercontent.com/24695764/53610338-59ee6280-3bc2-11e9-98e4-7ebacde65a6f.PNG)

Schwarzschild Module is about calculation, not plotting. One-liner after the heading needs to be changed.
![2](https://user-images.githubusercontent.com/24695764/53610405-aa65c000-3bc2-11e9-8518-8bcabc7d3c79.PNG)

Hyperlinking to other sphinx docs is not happening. Kindly, see the docstrings and generated docs.
![3](https://user-images.githubusercontent.com/24695764/53610588-58716a00-3bc3-11e9-9010-101220736878.PNG)

![4](https://user-images.githubusercontent.com/24695764/53610595-5e674b00-3bc3-11e9-8f34-2714f17b2bd6.PNG)

![5](https://user-images.githubusercontent.com/24695764/53610687-a4241380-3bc3-11e9-9a62-72002e2b6339.PNG)

**Comment by ritzvik** [comment]
Module name fix tried
#74

**Comment by shreyasbapat** [comment]
@spino17 @ritzvik  Kindly push a user guide

**Comment by ritzvik** [comment]
PR #88 also fixes : 
 Sub-bulleted list not rendering in "What's New"

![7](https://user-images.githubusercontent.com/24695764/53720759-6b9d6780-3e59-11e9-8467-76c511dd2ae9.PNG)
