### ISSUE TITLE
Leverage the symmetry of christoffel symbols to ease it's calculation for Kerr Metric

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#108]
🐞 **Problem**
Kerr Metric is symmetric over its lower indices. That is Y<sup>i</sup><sub>kl</sub> = Y<sup>i</sup><sub>lk</sub>. However this is not being leveraged for faster computation as of now.

🎯 **Goal**
Re-implement function `christoffels()` in `utils/kerr_utils.py` to make it faster

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #108`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
@shreyasbapat assign it appropriate labels including good-first-issue

**Comment by raphaelreyna** [comment]
I can try to do this.
