### ISSUE TITLE
Coding the right event horizon for Kerr & Kerr-Newman space-time

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#109]
🐞 **Problem**
As of now, in calculation of time-like trajectory in Kerr metric stops and raises a warning on reaching schwarzschild radius. But event horizon in kerr spacetime is smaller than schwarzschild radius. But the exact values need to be researched.

🎯 **Goal**
  - Research about the problem and specify the correct radius after which computation should stop in `metric/kerr.py`.

- [x] Kerr

- [ ] Kerr-Newman

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #109`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
Do the same for Kerr-Newman space time also.

**Comment by shilpi1958** [comment]
Hi, I would like to work on this issue.
So I found that horizon for Kerr spacetime has equation r = M + sqrt(M^2  - a^2).
I shall define a variable kerr_horizon equal for the same and change the limit (from Schwarzschild radius) and also change the warning.

Is this correct?

**Comment by ritzvik** [comment]
> Hi, I would like to work on this issue.
> So I found that horizon for Kerr spacetime has equation r = M + sqrt(M^2 - a^2).
> I shall define a variable kerr_horizon equal for the same and change the limit (from Schwarzschild radius) and also change the warning.
> 
> Is this correct?

@shilpi1958 As the core function of event horizon is already implemented `utils/kerr_utils.py` you can use that to provide new limits in `metric/kerr.py`.

Kindly go ahead with the issue.

Thanks for your interest 🙂

**Comment by shilpi1958** [comment]
hey,
I made a pull request for this issue
[https://github.com/einsteinpy/einsteinpy/pull/151](url)

**Comment by ritzvik** [comment]
@ritzvik Reopened the issue because Kerr-Newman still needs to be taken care of.

**Comment by obi-wan-shinobi** [comment]
I would like to work on this issue :)
