### ISSUE TITLE
Refactor some functions in Schwarzschild and Kerr class

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#113]
🐞 **Problem**
`calculate_trajectory()` and `calculate_trajectory_iterator()` in both `metric/schwarzschild.py` and `metric/kerr.py` have become a mess. Refactoring is required.

🎯 **Goal**
  - Refactor them such that both `cyclometic` and `cognitive` complexity remains low.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #113`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by yashrsharma44** [comment]
Can I take this issue?

**Comment by ritzvik** [comment]
> Can I take this issue?

Could you discuss it here how you aim to tackle the problem?

**Comment by rishi-s8** [comment]
@ritzvik I'd like to work on this issue. :) I'll think about how to implement this and get back to you. Meanwhile, can you please assign this to me?

**Comment by aptus-jaime** [comment]
Hi I hope to be a new contributor at some point but I was quite confused by this issue.  Why is there seperate geodesic solvers for each metric?  Wouldn't a generic solver which takes in a metric class be best?  I've implemented something similar in C in the past:

https://github.com/jaime-varela/Geodesic-solver

**Comment by jman27182818** [comment]
Hi I hope to be a new contributor and I was a bit confused on this issue.  Why is there a seperate ODE integrator for each metric?  Wouldn't a generic integrator which takes in a metric class be best?

I implemented basic prototype like this in C in the past:

https://github.com/jaime-varela/Geodesic-solver

**Comment by ritzvik** [comment]
Solving geodesic equations with arbitrary initial positions & velocity requires 2 things, Christoffel Symbols and a tensor which is differential of Metric Tensor w.r.t. each component(time and space). So we have to explicitly define these 2 tensors also, apart from the metric tensor.

Also calculating Schwarzschild Geodesics is much simpler because the Christoffel Symbols are 0 at most of the indices. Same for Kerr upto a lesser extent. A generic solver would not try to leverage these features. 

These problems do not allow us to implement a generic solver.

  - Any idea how to generalize things without losing significant performance is welcome :)



> Hi I hope to be a new contributor

Thanks for your interest @jman27182818 ! You are more than welcome :)

**Comment by ritzvik** [comment]
@jman27182818 Come, drop a hi at https://riot.im/app/#/room/#einsteinpy:matrix.org or https://gitter.im/EinsteinPy-Project/EinsteinPy . These are our community chatrooms and both are bridged!
