### ISSUE TITLE
BL and Normal Coordinate Transformation : Confusion in Names!

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#115]
🐞 **Problem**

There is lot of confusion in coordinates transformation! 
`bl_coord_transforms` and `coord_transforms` are not good names as in the `coord_transforms` does not specify the type of coordinates it works on while `bl_coord_transforms` clearly tells user what the module does! There is a need to make the coord transforms more intuitive.

🎯 **Goal**

Make coordinate transformations more intuitive in EinsteinPy

💡 **Possible solutions**

* Rename `coord_transforms.py`
* Merge both files into one
* Think of some other solution?

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #115`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
How about we create a separate module called `coords` in Einsteinpy.
We can have `sph_crt.py` for Spherical<->Cartesian conversions, `bl_crt.py` for Boyer-Lindquist<->Cartesian conversions & maybe `sph_bl.py` for spherical<->Boyer-Lindquist conversions.

Still the names feel weird. Any suggestions?

**Comment by raphaelreyna** [comment]
It may possibly be too heavy handed, but what about subclassing numpy.array to make a vector class that knows what its current coordinate system is and how to convert itself to any other given coordinate system?

**Comment by ritzvik** [comment]
> It may possibly be too heavy handed, but what about subclassing numpy.array to make a vector class that knows what its current coordinate system is and how to convert itself to any other given coordinate system?

Maybe, it's a long shot. But we'll keep it in tabs. Open an issue wherever necessary.
