### ISSUE TITLE
Change indexing style in numpy arrays

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#116]
🐞 **Problem**
To access an element of a 3-d array a, we have been doing `a[i][j][k]` which is slow as a copy of `a[i]` and `a[i][j]` is being created and discarded. Same for 2-d arrays where things are accessed by `a[i][j]`. I believe things are becoming slow for the reason

🎯 **Goal**
  - convert 3-d array indexing from `a[i][j][k]` to `a[i, j, k]` wherever applicable.
  - convert 2-d array indexing from `a[i][j]` to `a[i, j]` wherever applicable.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #116`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
Can you point out where the changes are required?

**Comment by ritzvik** [comment]
> Can you point out where the changes are required?

I think it's everywhere
https://github.com/einsteinpy/einsteinpy/blob/master/src/einsteinpy/metric/kerr.py#L118-L151
https://github.com/einsteinpy/einsteinpy/blob/master/src/einsteinpy/utils/kerr_utils.py#L116-L125

I mean wherever indexing is like `[1][2]` in numpy arrays, it's required to convert them to `[1, 2]`

**Comment by ritzvik** [comment]
This issue has been partially fixed in #128 . Now, just a few more instances of the problem remain in `utils/kerr_utils.py`

**Comment by shilpi1958** [comment]
Hi,
I have changed the instances in utils/kerr_utils.py
[https://github.com/einsteinpy/einsteinpy/pull/148]
