### ISSUE TITLE
Make a utility file for BL/Spherical coordinate conversion

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#118]
🐞 **Problem**
The title is self-explanatory.

💡 **Possible solutions**

  - Direct conversion formulas can be written
  - or, In order to make coder's life easy, conversions can be done using Cartesian in between. That is `Spherical->Cartesian->Boyer Lindqiuist` and vice versa.
  - Code it in the lines of `utils/coord_transforms.py` and 
`utils/bl_coord_transforms.py`

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #118>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
This issue is on hold until #121 is fixed.

**Comment by shreyasbapat** [comment]
Closed in #176
