### ISSUE TITLE
Further Leverage the symmetry of christoffel symbols to ease it's calculation for Kerr Metric

### ISSUE THREAD

**Issue by raphaelreyna** [einsteinpy/einsteinpy#119]
🐞 **Problem**

Kerr Metric is symmetric over its lower indices. That is Yikl = Yilk. However this is not being leveraged enough for faster computation as of now.

🎯 **Goal**

Re-implement function `christoffels()` in `utils/kerr_utils.py` to make it faster

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
After #120 gets merged, I doubt further improvements can be done on `christoffels()`. Maybe we should divert ourselves to optimize `metric()`, 'metric_inv()`, and `dmetric_dx()` after that.

**Comment by shreyasbapat** [comment]
Thanks @raphaelreyna for your support!
