### ISSUE TITLE
Clean the Messed up utils!

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#121]
🐞 **Problem**

The `utils` module is currently too messed up. 

🎯 **Goal**

💡 **Possible solutions**

Make necessary changes to clean it. Refactor modules, code.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
It is a serious issue and it can addressed after an extensive discussion here about the new structure of utils.

**Comment by pmk21** [comment]
How about making coordinates into an object with methods, instead of using many functions to transform between coordinates? And probably split the other files in utils into meaningful modules.

**Comment by shreyasbapat** [comment]
That's correct. I will suggest making a base class for coordinates and writing other coordinates class on top of it!

**Comment by shreyasbapat** [comment]
Creating a whole new infrastructure for Coordinates

**Comment by ritzvik** [comment]
Some proposed changes from my side.

We need some changes in the parameters of functions in `utils` namely, `kerr_utils.py`,`kerrnewman_utils.py`, `schwarzschild_utils.py` when #128 is merged. 
  - Firstly, wherever the functions take `Rs`, i.e schwarzschild radius as an input, replace them with `M`,`G`, and `c` and calculate `Rs = 2*G*M/(c**2)` inside the function itself. We can't expect the user to supply schwarzschild radius. While implementing it, leave out function `delta()` in both `kerr_utils.py` and `kerrnewman_utils.py`.
  - Currently functions are like `func(c, G, Cc, r, theta.....)`. Here the fundamental constants need to be optional arguments and therefore, should be last few parameters.
    - `c` is Speed of light. Default value : `einsteinpy.constant.c.value`
    - `G` is gravitational constant. Default value : `einsteinpy.constant.G.value`
    - `Cc` is coulomb's  constant. Default value : `einsteinpy.constant.coulombs_const.value`

**Comment by shreyasbapat** [comment]
> Firstly, wherever the functions take Rs, i.e schwarzschild radius as an input, replace them with M,G, and c and calculate Rs = 2*G*M/(c**2) inside the function itself. We can't expect the user to supply schwarzschild radius. While implementing it, leave out function delta() in both kerr_utils.py and kerrnewman_utils.py.

We have a function to calculate exactly that!

**Comment by ritzvik** [comment]
> > Firstly, wherever the functions take Rs, i.e schwarzschild radius as an input, replace them with M,G, and c and calculate Rs = 2_G_M/(c**2) inside the function itself. We can't expect the user to supply schwarzschild radius. While implementing it, leave out function delta() in both kerr_utils.py and kerrnewman_utils.py.
> 
> We have a function to calculate exactly that!

I believe the function takes input along with astropy.units, maybe we ca make a separate private function to take in normal float & integers.

**Comment by shreyasbapat** [comment]
Can be closed for now :)
