### ISSUE TITLE
Benchmark and Validate the core Schwarzschild and Kerr Algorithms

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#122]
🐞 **Problem**

Perform benchmark testing for both the algorithms. Because how do anyone know that the algorithms are correct? 

🎯 **Goal**

To get clear understanding on performance of algorithm and its validation.

💡 **Possible solutions**

Validate against the industry standard or the books etc. Publish clear cut benchmarking results.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by JeS24** [comment]
I am currently validating the methods in `einsteinpy.metric.Kerr` and `einsteinpy.metric.Schwarzschild`, as this is necessary to ensure the correctness of the null geodesics. We can add whatever tests result from this to `test_metric`.

**Comment by JeS24** [comment]
@shreyasbapat  Does "benchmark" refer to how close our results are to published studies? In that case, the calculation and plots, that will be obtained from the GSoC additions to `geodesics` and `rays`, can perhaps serve as a benchmark.

**Comment by shreyasbapat** [comment]
> @shreyasbapat Does "benchmark" refer to how close our results are to published studies? In that case, the calculation and plots, that will be obtained from the GSoC additions to `geodesics` and `rays`, can perhaps serve as a benchmark.

Yes. Precisely
