### ISSUE TITLE
Add a plotting utility for Kerr Black holes

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#123]
🐞 **Problem**

As in https://github.com/einsteinpy/einsteinpy/blob/master/docs/source/examples/Visualizing%20event%20horizon%20and%20ergosphere%20of%20Kerr%20black%20hole.ipynb

It clearly lacks plotting support from einsteinpy side.

🎯 **Goal**

Make a better plotting module for it

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by pmk21** [comment]
I'd like to solve this. Any suggestions on solving this issue?

**Comment by shreyasbapat** [comment]
We can create a plotting module for plotting the Event horizon! Might be 3D too!

**Comment by Varunvaruns9** [comment]
Hi @pmk21 ,
are you still working on it? If not I would like to work on this.

**Comment by shreyasbapat** [comment]
Geodesics module will do the required!
