### ISSUE TITLE
Inconsistencies in badges

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#125]
🐞 **Problem**
Not all badges in `README.rst`  are fetched from `shields.io`. Therefore, `flat-square` style can't be applied on all the badges which is creating inconsistencies across README and ReadTheDocs.

🎯 **Goal**
  - Fetch all the badges from `shields.io` with `flat-square` style
  - Changes to be made in `README.rst` and `Docs/source/index.rst`

💡 **Possible solutions**
  - Some badges are given below which can be replaced
    - https://img.shields.io/gitter/room/EinsteinPy-Project/EinsteinPy.svg?logo=gitter&style=flat-square
    - https://img.shields.io/matrix/einsteinpy:matrix.org.svg?logo=riot&style=flat-square
    - https://img.shields.io/appveyor/ci/shreyasbapat/einsteinpy.svg?logo=appveyor&style=flat-square
    - https://img.shields.io/codeclimate/maintainability/einsteinpy/einsteinpy.svg?logo=code-climate&style=flat-square

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #125`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by divya144** [comment]
Hi
I would like to fix this issue.

**Comment by ritzvik** [comment]
> Hi @ritzvik
> I would like to fix this issue.

Thanks for your interest. It's all yours!

**Comment by shreyasbapat** [comment]
Closed #125 in #146
