### ISSUE TITLE
Make the tests on CI parallel

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#126]
🐞 **Problem**
As of now, the tests on various CI are running sequentially. It's not a problem right now, but we might want to run them in parallel as the number of tests grows.

🎯 **Goal**
  - Parallelize the tests on `TravisCI`, `CircleCI` and `appveyor`.

💡 **Possible solutions**
  - On personal computer, tests are be parallelized by `pip install pytest-xdist` and then `pytest -n 8 -vv`
  - Maybe this could be the way. See https://docs.pytest.org/en/3.0.0/xdist.html
  - After figuring out the solution, change the `.yml` files for each of the CIs

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #126`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by yashrsharma44** [comment]
Can I work on this issue?

**Comment by ritzvik** [comment]
> Can I work on this issue?

Great. Go ahead!
Thanks for trying to solve this one @yashrsharma44
