### ISSUE TITLE
Raise proper warning when sympy is not installed!

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#131]
🐞 **Problem**
Sympy is an optional dependency! We should let users know about this!

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by rishi-s8** [comment]
I'd like to work on this. Can you help me with in what way is the warning needed, and how should I go about doing it?

**Comment by rishi-s8** [comment]
@shreyasbapat

**Comment by shreyasbapat** [comment]
If you look carefully at the `setup.py` , sympy is an optional dependency, and we only let users install it when they run einsteinpy[dev], which is unintuitive. We would like to raise a warning if sympy is not installed and user tries importing this: https://github.com/einsteinpy/einsteinpy/blob/master/src/einsteinpy/utils/christoffel.py
Easy to fix :)
