### ISSUE TITLE
Update package description everywhere

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#134]
🐞 **Problem**

The package description has got quite old and needs a revival! 
🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
### E-mail in `CODE_OF_CONDUCT.rst` needs to be changed.

**Comment by shreyasbapat** [comment]
@ritzvik I have assigned this to you :)
