### ISSUE TITLE
Move to setup.cfg

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#135]
🐞 **Problem**

Migrate from setup.py to setup.cfg!
🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by yashrsharma44** [comment]
Hey @shreyasbapat , I wanted to work on this issue!
Presently, I see a `setup.cfg` file exists, so is the issue solved, or are we looking to add more metadata to `setup.cfg`?

**Comment by shreyasbapat** [comment]
Hi! @yashrsharma44 . We plan to move to `setup.cfg` completely. 
https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files

Thanks to https://gitlab.com/librespacefoundation/satnogs/satnogs-client/
