### ISSUE TITLE
Mobile compatibility of Documentation

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#138]
🐞 **Problem**

The documentation does not adapt to some mobile width's. Particularly: https://github.com/bitprophet/alabaster/issues/139 

We are still waiting to get the PR https://github.com/bitprophet/alabaster/pull/140 . Its milestoned for 0.8, but I am not sure if it will arrive soon. 

🎯 **Goal**

Meanwhile we can fix it in our own documentation by overriding some settings. 

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by divya144** [comment]
@shreyasbapat I would like to work on this issue.

**Comment by shreyasbapat** [comment]
Sure thing! Go ahead :)

**Comment by shreyasbapat** [comment]
@divya144 Are you still working on it?

**Comment by shreyasbapat** [comment]
Closed in #171
