### ISSUE TITLE
Organize and reorder utils for Kerr, Kerr-Newman and Schwarzschild metrics

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#141]
🐞 **Problem**
As of now, various useful functions used by `metric/schwarzschild.py` are in `utils/schwarzschild_utils.py`. Same goes for `metric/kerr.py` and `metric/kerrnewman.py`. We need to move these functions out of `utils` and make them a core part of library as they are quite-useful even when used stand-alone.

🎯 **Goal**

  - Migrate them somewhere, so as to make them look like a core part of library.
  - Reorder the parameters inside the functions, so as parameters like `c`, `G` etc are made to be optional with default values can be taken in SI units from `constant.py`.
  - Many functions take `Rs` as parameters which is Schwarzschild Radius. However, there is no sense to keep parameters `Rs` as it can be calculated from more fundamental things like mass, speed of light(`c`), gravitational constant(`G`). `Rs = 2*M*G/square(c)`.
  - These changes would break the API, and therefore requires updation of tests and example notebooks.

⏫ **Progress**

The tasks to be taken up in separate PRs
  - [x] Reorder parameters within functions
  - [ ] Move the functions somewhere more suitable

💡 **Possible solutions**

  - Firstly, wherever the functions take `Rs`, i.e schwarzschild radius as an input, replace them with `M`,`G`, and `c` and calculate `Rs = 2*G*M/(c**2)` inside the function itself. We can't expect the user to supply schwarzschild radius. While implementing it, leave out function `delta()` in both `kerr_utils.py` and `kerrnewman_utils.py`.

  - Currently functions are like `func(c, G, Cc, r, theta.....)`. Here the fundamental constants need to be optional arguments and therefore, should be last few parameters like `func(r, theta, ..... , c=default_value, G=default_value, Cc=default_value)`. Leave out `G` and `Cc` whenever not required.
    - `c` is Speed of light. Default value : `einsteinpy.constant.c.value`
    - `G` is gravitational constant. Default value : `einsteinpy.constant.G.value`
    - `Cc` is coulomb's  constant. Default value : `einsteinpy.constant.coulombs_const.value`
  - After the changes, the API would break, therefore, update the example notebooks.
  - Update the user guide
  - Update the tests

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #141`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
This issue is very closely related to #121 . I mentioned this issue as a comment there but it may be more apt to make this a separate one.

**Comment by ritzvik** [comment]
@shreyasbapat This can also be a `good-first-issue` I guess.

**Comment by shreyasbapat** [comment]
I think it's harder

**Comment by alpeshjamgade** [comment]
i  would like too work on this. :)

**Comment by ritzvik** [comment]
> i would like too work on this. :)

Great ! go ahead.
Focus on task 1 initially.
Thanks @alpeshjamgade

**Comment by alpeshjamgade** [comment]
#194 Organize and reorder utils for Kerr, Kerr-Newman and Schwarzschild metrics

**Comment by alpeshjamgade** [comment]
@ritzvik can you give names of function which we should take out of utils.py.

**Comment by ritzvik** [comment]
> @ritzvik can you give names of functions which we should take out of utils.py.

We would finalize #194 first. Then we would look into it.

**Comment by alpeshjamgade** [comment]
#196  Reorder parameters within functions

**Comment by alpeshjamgade** [comment]
> 
> 
> > @ritzvik can you give names of functions which we should take out of utils.py.
> 
> We would finalize #194 first. Then we would look into it.

@ritzvik i want to work on the second task.
can you tell me which functions we should move out of utils? i have some in my mind but im not sure about that?

**Comment by alpeshjamgade** [comment]
i thought of making a module core.py and putting the functions in there.
is it fine? or can you suggest something better?

**Comment by ritzvik** [comment]
> i thought of making a module "core.py" and putting the functions in there.
> is it fine? or can you suggest something better?

@alpeshjamgade Reorganizations is also being undertaken in the core metric modules in PR #203 . We have to wait for a while to work on this. I'll notify when the time is right :) . BTW thanks for taking this up.

**Comment by JeS24** [comment]
Almost all of the utilities have been moved into `metric` itself, in #512.
