### ISSUE TITLE
Remove all the unnecessary pytest.mark.parametrize

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#142]
🐞 **Problem**

Tests are currently parametrized on single set of values. `pytest.mark.parametrize` has a different essence. Remove the redundant test data from everywhere. Add pytest fixtures wherever required. 
https://docs.pytest.org/en/latest/parametrize.html

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Manvi07** [comment]
Hi @shreyasbapat 
I went through the documentation of the Parametrizing function. But the issue is not clear yet. Could you please give a little more explanation on what is to be done? Also, what does adding Pytest fixtures imply?

**Comment by shreyasbapat** [comment]
Hi @Manvi07 :) 
So, have a look at tests like this: 
https://github.com/einsteinpy/einsteinpy/blob/master/src/einsteinpy/tests/test_metric/test_kerrnewman.py#L55
parametrizing is not made for this, it is when you want to pass multiple inputs while testing. This increases the complexity of testing. We would like to have them hardcoded inside the testing function. Or if you think the same data is being used in a lot of places, you can make a fixture for that.
Here is the doc of fixture: https://docs.pytest.org/en/latest/fixture.html

**Comment by Manvi07** [comment]
Alright. I would like to work on this issue :)
