### ISSUE TITLE
Implement the event horizon and ergosphere of Kerr-Newman black holes

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#147]
🐞 **Problem**
We need functions to calculate the event horizon and ergosphere of Kerr-Newman black holes.
It can help towards fixing #109 

🎯 **Goal**
Implementing them on the lines of Event Horizon and Ergosphere functions in `utils` for `Kerr`.

💡 **Possible solutions**
Link to the relevant equations.
https://en.wikipedia.org/wiki/Kerr%E2%80%93Newman_metric#Important_surfaces

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #147`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
Isn't this similar to #109 ? Why do we need a separate issue?

**Comment by ritzvik** [comment]
> Isn't this similar to #109 ? Why do we need a separate issue?

This issue is about coding the functions related to event horizon and ergosphere in `utils`.
#109 is about implementing them in `Kerr` & `KerrNewman` class so that it can raise a warning when a test particle crosses the event horizon.

**Comment by ritzvik** [comment]
@shreyasbapat Should I close this? Suggestions?

**Comment by shreyasbapat** [comment]
Yes maybe. We should not have redundant issues :)

**Comment by ritzvik** [comment]
Closing 👍
