### ISSUE TITLE
Attractor Radius in StaticGeodesicPlotter is too less

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#150]
🐞 **Problem**

Due to the radius issues, the plots are not shown properly. Most of the times, they miss an Attractor.

🎯 **Goal**

Think of a strategy to get good plots!

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by rtanmay** [comment]
I would like to work on this issue, can you assign this to me?
Thanks

**Comment by shreyasbapat** [comment]
Sure go ahead!
