### ISSUE TITLE
Ill formatted links in Jupyter Notebook

### ISSUE THREAD

**Issue by rishi-s8** [einsteinpy/einsteinpy#153]
🐞 **Problem**
Links in example jupyter notebook ```index.ipynb``` are not working

Looks like the use of markdown is out of syntax.

🎯 **Goal**

Fix syntax of markdown to correct the links.

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by rishi-s8** [comment]
I am working on this issue.

**Comment by rishi-s8** [comment]
![Screenshot 2019-04-07 at 12 38 44 PM](https://user-images.githubusercontent.com/33762894/55680078-a9971b00-5932-11e9-90be-f2f282e0f0e9.png)

Here's the current markdown
```
## [Visualizing advance of perihelion of a test particle in Schwarzschild space-time](docs/source/examples/Visualizing advance of perihelion of a test particle in Schwarzschild space-time.ipynb)

[![orbit](docs/source/examples/perihelion_advance.png)](docs/source/examples/Visualizing advance of perihelion of a test particle in Schwarzschild space-time.ipynb)
```

**Comment by shreyasbapat** [comment]
Do you mean this notebook? https://mybinder.org/v2/gh/einsteinpy/einsteinpy/master?filepath=index.ipynb

**Comment by shreyasbapat** [comment]
This actually works fine. But yes, in local machines, it may look ugly. Can you try using iPyhon magic `%%markdown` for every cell?

**Comment by shreyasbapat** [comment]
Well, might be related : https://github.com/jupyter/notebook/issues/3874

**Comment by rishi-s8** [comment]
Well I am testing links with local Jupyter notebook..
Links of the type ```www.google.com``` are working, but the local link to another *.ipynb is not working this way.

**Comment by rishi-s8** [comment]
```%%markdown``` is rendering the same thing.

**Comment by rishi-s8** [comment]
@shreyasbapat  I tested with different links locally, I found that markdown is not supporting links with ```spaces```.
So there are two solutions I can propose:
1. Insert ```&#32;``` in every place where there is ```space``` in the links.
2. Change the spaces in filenames to some other character like ```_```.

Which one would you prefer I do?

**Comment by shreyasbapat** [comment]
I believe solution 1 will be an extra effort needed everytime. I will go with solution 2. :)
