### ISSUE TITLE
Create einsteinpy.bodies module

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#154]
🐞 **Problem**

We have to define explicitly about the bodies. It would be nice to have a class for that as well. 
🎯 **Goal**

💡 **Possible solutions**

Add mass for attractor bodies and r,v for other.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shilpi1958** [comment]
hey, I would like to work on this.
I don't clearly understand the issue
Can you elaborate a bit?

**Comment by rtanmay** [comment]
I have understood the problem. Can you assign the task to me @shreyasbapat ?
Thanks

**Comment by shreyasbapat** [comment]
I can't assign this task to @rtanmay ! Sorry for that! Both of you try. The first pull request to get green ticks on every check will be merged. :)
