### ISSUE TITLE
Color options in ScatterGeodesicPlotter and StaticGeodesicPlotter is missing.

### ISSUE THREAD

**Issue by rtanmay** [einsteinpy/einsteinpy#156]
🐞 **What bugs you?**
Color options for attractor and scatter plots are not present in the classes ScatterGeodesicPlotter and StaticGeodesicPlotter.

🎯 **Goal**
This change can benefit people in the way that if they want to create many plots, It can help them in distinguishing a certain plot in a group of plots. Also it gives user to option to use his/her favorite color.

💡 **Possible solutions**
The possible solution is to use a parameter for the user to pass the color while making the class. If the user does not want to pass the parameter, we can default it to some color.

📋  **Steps to solve the problem**
I have created and tested the class with added parameters. Will create a PR after writing this issue.
 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by rtanmay** [comment]
Creating a PR with the results in around 10 minutes.

**Comment by shreyasbapat** [comment]
Great addition. Thanks :)
