### ISSUE TITLE
Adding the packages in requirements.txt

### ISSUE THREAD

**Issue by yashrsharma44** [einsteinpy/einsteinpy#162]
## Adding list of packages in `requirements.txt`
🐞 **What bugs you?**

Currently, no list of packages exists for `einsteinpy` in `requirements.txt`. It would be better to add all the dependencies in the `requirements.txt`.

🎯 **Goal**

Adding entries to `requirements.txt`

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by yashrsharma44** [comment]
I am taking this issue.

**Comment by shreyasbapat** [comment]
No dependencies are there in `requirements.txt` for a reason. All of them are there in the `setup.py` and are installed automatically. I am closing this issue!
