### ISSUE TITLE
Suppress the output for pip installs in various CIs

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#165]
🐞 **Problem**
`pip install something` in continuous integration services TravisCI and Appveyor produces a whole bunch of output which is not really necessary.

🎯 **Goal**
  - use `--quiet` option with pip installs to suppress the outputs.
  - Also update pip each time before pip installs by using `pip install --upgrade pip --quiet` 

💡 **Possible solutions**
  - Edits need to be done in `appveyor.yml` and `.travis.yml`
  - For a reference, see `.circleci/config.yml`

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Fixes #165`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by agarwalr98** [comment]
@ritzvik I will try to solve this prob.Thanks

**Comment by ritzvik** [comment]
@agarwalr98 I believe someone else has already started working on it.

**Comment by agarwalr98** [comment]
okk, but let me know if someone has not started because I did spend some amount of time on it.
