### ISSUE TITLE
Consistent tests for calculate trajectory function in Scwarzschild

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#168]
🐞 **Problem**
Even though, schwarzschild and kerr geometries are pretty similar, their tests seem different.

🎯 **Goal**
  - Edit `test_calculate_trajectory()` in `tests/test_metric/test_schwarzschild.py` on the lines of same function present in `test_kerr.py` for consistency.
  - Get the schwarzschild metric by `from einsteinpy.utils import schwarzschild_utils` and `g = schwarzschild_utils.metric()`

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Fixes #168`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
@shreyasbapat Seems like a good first issue

**Comment by alpeshjamgade** [comment]
i would like to work on this.

**Comment by ritzvik** [comment]
> i would like to work on this.

@alpeshjamgade Thanks for your interest.
Issue is all yours!

**Comment by shreyasbapat** [comment]
My question is why do you want consistency in tests?

**Comment by ritzvik** [comment]
> My question is why do you want consistency in tests?

When the test was written, `metric()` was not there in `schwarzschild_utils.py`. Now that it is there, it seems like a good idea that `test_calcultate_trajectory()` in `test_schwarzschild.py`, `test_kerr.py` and `test_kerrnewman.py` follows the same pattern. Plus, it was also a good first issue.

**Comment by shreyasbapat** [comment]
> When the test was written, metric() was not there in schwarzschild_utils.py. Now that it is there, it seems like a good idea that test_calcultate_trajectory() in test_schwarzschild.py, test_kerr.py and test_kerrnewman.py follows the same pattern. Plus, it was also a good first issue.

Great!

**Comment by shreyasbapat** [comment]
> When the test was written, metric() was not there in schwarzschild_utils.py. Now that it is there, it seems like a good idea that test_calcultate_trajectory() in test_schwarzschild.py, test_kerr.py and test_kerrnewman.py follows the same pattern. Plus, it was also a good first issue.

Great!
