### ISSUE TITLE
No event horizon function for Kerr- Newman Blackhole present

### ISSUE THREAD

**Issue by shilpi1958** [einsteinpy/einsteinpy#172]
🐞 **What bugs you?**
There isn't a function for for Kerr- Newman Black hole present in kerrnewman_utils.py

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
#109 Already addresses this, I guess. Close this if you see fit.
Nice observation BTW. Thanks @shilpi1958

**Comment by shilpi1958** [comment]
oh okay!
