### ISSUE TITLE
SOCIS Ideas link not working

### ISSUE THREAD

**Issue by Masquerade0097** [einsteinpy/einsteinpy#175]
🐞 **Problem**

The link to [SOCIS](https://socis.esa.int/projects/) Ideas of EinsteinPy  does not work. It is similar to the following for different projects.
https://github.com/einsteinpy/einsteinpy/wiki/SOCIS-Ideas#adaptive-mesh-refinement-for-einsteinpy

🎯 **Goal**

The link needs to be fixed. It should point to the existing SOCIS 2019 Ideas wiki in the repo.

**Comment by Tushar-Tyagi** [comment]
Can I solve the issue?

**Comment by Tushar-Tyagi** [comment]
The link in the SOCIS website is : https://github.com/einsteinpy/einsteinpy/wiki/SOCIS-Ideas#adaptive-mesh-refinement-for-einsteinpy
But actually, it should be : https://github.com/einsteinpy/einsteinpy/wiki/SOCIS-2019-Ideas#adaptive-mesh-refinement-for-einsteinpy

**Comment by Tushar-Tyagi** [comment]
I think, you can't the change the link in SOCIS website ( xD ). It's better to change our wiki.
- [ ] Just change the title of that wiki page from *SOCIS-2019-Ideas* to **SOCIS-Ideas** .
I guess we don't have access to create/edit a wiki. ( Do we? )

**Comment by Tushar-Tyagi** [comment]
Solved.

**Comment by shreyasbapat** [comment]
Oh! It was me! Hehe

**Comment by shreyasbapat** [comment]
Thanks @Tushar-Tyagi :)

**Comment by shreyasbapat** [comment]
Closed in https://github.com/einsteinpy/einsteinpy/wiki/SOCIS-Ideas/434388396f0b4f2dc914304625a24f27975d2cf5
