### ISSUE TITLE
Bring in interactive plotting

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#179]
🐞 **Problem**

Static plotting is not much useful. We should get both 3D and 2D interactive plots. 
🎯 **Goal**

💡 **Possible solutions**
Use plotly

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by rtanmay** [comment]
@shreyasbapat  Can you assign this to me? I am making the dynamic plots so I will add dynamic nature for 3D plots as well

**Comment by Varunvaruns9** [comment]
@rtanmay I will be integrating a 3D plotting system and a module for interactive plotting as a followup for #123 . Thanks for asking :)

**Comment by rtanmay** [comment]
Alright @Varunvaruns9

**Comment by shreyasbapat** [comment]
No. I guess both of you misunderstood this issue :) 

I am talking of interactive plots. Where you can freely interact with the plots, move things around etc. :) However I won't assign this to anyone :)

**Comment by Varunvaruns9** [comment]
Yes, I thought the issue was for controlled animations at first but I made some progress for interactive plots as well. I looked up mpld3, bcoz I was looking for something which required a minimum code change. I'll try to get it to work or else try something else like plotly.

**Comment by shreyasbapat** [comment]
I would highly discourage you for mpl3d. They just couldn't make it work. For plotly <3

**Comment by shreyasbapat** [comment]
Also, I would like to draw the attention to `Figurewidget` by plotly

**Comment by shreyasbapat** [comment]
#274 Closes this!
