### ISSUE TITLE
website URL not working

### ISSUE THREAD

**Issue by vinaybommana** [einsteinpy/einsteinpy#18]
🐞 **Problem**
website url for github.io not working

![einsteinpy](https://user-images.githubusercontent.com/16438494/52262741-5402ba00-2953-11e9-9cb6-414788f46c46.PNG)

while follow the link, I am getting 404 error
![image](https://user-images.githubusercontent.com/16438494/52262773-6ed52e80-2953-11e9-8465-8b06527e88c1.png)

**Comment by shreyasbapat** [comment]
Hello @vinaybommana , thanks for checking. We are currently developing the website and would really appreciate contributions. The library is under serious development and we would take some time to develop the website. If you are interested to contribute to the project, checkout these issues: https://github.com/einsteinpy/einsteinpy/issues

You can also contribute to the website project: https://github.com/einsteinpy/einsteinpy.github.io if you wish to.

We are really grateful for your effort. Thanks!

**Comment by shreyasbapat** [comment]
I will further mark this for 0.1 milestone.

**Comment by shreyasbapat** [comment]
I think we can close it! 
@vinaybommana We have deployed a website/blog! You can check it out!
Thanks for the motivation!
