### ISSUE TITLE
Enable EPOCHS!

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#182]
🐞 **Problem**

Right now we don't care what is the time when we started. But this should not be the case
🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
Could you elaborate it more? Didn't get it 😄

**Comment by shreyasbapat** [comment]
Epoch is self sufficient. Every event in history is time dependent, and we should take care of when that is happening. Epoch is counted from some standards, like J2000 or so!

**Comment by rtanmay** [comment]
@shreyasbapat Can you assign this issue to me?

**Comment by shreyasbapat** [comment]
Add J2000 :)
