### ISSUE TITLE
Isort conflicts with Black

### ISSUE THREAD

**Issue by rishi-s8** [einsteinpy/einsteinpy#185]
🐞 **Problem**
Isort and black are formatting import differently in ```coordinates/__init__.py```

Referencing https://github.com/ambv/black/issues/127
Referencing reopened https://github.com/timothycrosley/isort/issues/694

Temporary Solution:
Add # isort: skip in front of the import.
Implemented in https://github.com/einsteinpy/einsteinpy/pull/176

🖥
Issue with the following versions:
```isort v4.3.17```
```black v19.3b0```

🎯 **Goal**
Remove the temporary fix of isort: skip in ```coordinates/__init__.py```

💡 **Possible solutions**
Wait till the Issue is solved in Black or Isort

**Comment by shreyasbapat** [comment]
As pointed out by @Juanlu001 in chats: 
https://black.readthedocs.io/en/stable/the_black_code_style.html?highlight=isort#how-black-wraps-lines
