### ISSUE TITLE
Spelling errors in comments and documentation

### ISSUE THREAD

**Issue by rishi-s8** [einsteinpy/einsteinpy#198]
🐞 **Problem**
There are a lot of spelling errors in the comments and docstrings. One may also find some in the documentation, if you dig a bit deeper.

🎯 **Goal**
Well obviously, they pinch my eyes. So they need to be corrected. 
For a start, there are a few spelling errors in ```/tests/test_utils/test_kerrnewman_utils.py```

💡 **Possible solutions**
This is mostly to get people around the codebase. So explore and correct. 😄 

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
Specifically, an instance of this can be seen in `docs/source/metric.rst`. Some subtle but understandable errors are there.

**Comment by abhijeetmanhas** [comment]
I will be working on this issue. Please review the changes I have done in PR #202.

**Comment by shreyasbapat** [comment]
@abhijeetmanhas  A friendly suggestion from my side is, you always ask if you can work on the issue and not directly tell. :)
