### ISSUE TITLE
Change Warning Type in coordinate utils

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#200]
🐞 **Problem**
When executing `from einsteinpy.utils import something` `UserWarning` is raised.

🎯 **Goal**
Change warning type to `PendingDeprecationWarning`

💡 **Possible solutions**

See :
  - https://docs.python.org/3/library/exceptions.html#PendingDeprecationWarning
  - https://docs.python.org/3/library/warnings.html#warnings.warn

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by abhijeetmanhas** [comment]
I am taking up the issue. I will change warning category in `coord_transform.py` and `bl_coord_transform.py` files to `PendingDeprecationWarning`. 
Should I change warn category from `UserWarning` to `PendingDeprecationWarning` in `christoffel.py` too where warning is raised on importing sympy?

**Comment by ritzvik** [comment]
> I am taking up the issue. I will change warning category in `coord_transform.py` and `bl_coord_transform.py` files to `PendingDeprecationWarning`.
> Should I change warn category from `UserWarning` to `PendingDeprecationWarning` in `christoffel.py` too where warning is raised on importing sympy?

Great, the issue is yours!
No need to change warning in `christoffel.py`, it is not being deprecated as of now.
Thanks @abhijeetmanhas
