### ISSUE TITLE
DeprecationWarning raised by Matplotlib

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#206]
🐞 **Problem**
Matplotlib is raising `DeprecationWarning` in CircleCI Python 3.7 workflow.
![27](https://user-images.githubusercontent.com/24695764/56411488-8d826a80-629e-11e9-8ad6-4c1064d06092.PNG)

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Varunvaruns9** [comment]
I think this might be due to plotting modules using class `Schwarzschild`, which uses some methods that are going to be deprecated. It can be fixed by changing the given class to use new methods in `einsteinpy.coordinates`.

**Comment by alpeshjamgade** [comment]
![Screenshot from 2019-04-19 15-20-59](https://user-images.githubusercontent.com/44905974/56446416-5cfafa80-62b7-11e9-82be-addcebd6a1b5.png)

 @ritzvik not showing the warning on my machine

**Comment by shakeabi** [comment]
@ritzvik Did some digging. Seems like this error is prevailing across various packages. I believe this error has to be fixed in the matplotlib package itslef.

**Comment by shreyasbapat** [comment]
> @ritzvik Did some digging. Seems like this error is prevailing across various packages. I believe this error has to be fixed in the matplotlib package itself.

Correct! I didn't notice that! I will close this issue :) 
Thanks for chiming in @shakeabi
