### ISSUE TITLE
Two entries of same notebook in jupyter.rst! 

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#210]
🐞 **Problem**

The doc shows two links for a same notebook! And I doubt if we should even have that notebook in the example gallery! Ideas? 

🖥 **Please paste the output of following commands**

* `conda info -a` (only if you have conda)
* `conda list` (only if you have conda)
* `pip freeze`

<details>

```bash
# Paste your output here:

```
</details>

* `python -c "import einsteinpy.testing; einsteinpy.testing.test()"`

<details>

```bash
# Paste your output here:

```
</details>

🎯 **Goal**
![DeepinScreenshot_select-area_20190425123026](https://user-images.githubusercontent.com/24257914/56715716-16454e80-6756-11e9-81f0-b9cc03d18f63.png)

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyanshdwivedi** [comment]
@shreyasbapat I will like to take this up. May I?

**Comment by shreyasbapat** [comment]
Sure @shreyanshdwivedi :)

**Comment by fiterace** [comment]
@shreyanshdwivedi are you still working on this? If not, I will be glad to take this.

**Comment by shreyanshdwivedi** [comment]
@fiterace I'm busy with my exams. Please go ahead

**Comment by shreyasbapat** [comment]
Fixed in #248
