### ISSUE TITLE
Use tox for automating development process

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#211]
🐞 **Problem**

Tox provides amazing automation and is being used almost everywhere. 
🎯 **Goal**
https://tox.readthedocs.io/en/latest/

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by alpeshjamgade** [comment]
i would like to work on this.

**Comment by shreyasbapat** [comment]
Sure @alpeshjamgade ! Go ahead!
