### ISSUE TITLE
Update Jupyter Notebooks to account for the API breaking changes

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#212]
🐞 **Problem**
#203 PR introduced few API breaking changes in the `metric` module. The jupyter notebooks have, therefore, become outdated.

🎯 **Goal**
Update the notebooks in `docs/source/examples`. In short, do the required changes and rerun them.

💡 **Possible solutions**
See
  - http://docs.einsteinpy.org/en/latest/api/metric/metric_index.html
  - http://docs.einsteinpy.org/en/latest/api/coordinates/coordinates_index.html

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #212`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by fiterace** [comment]
@ritzvik i want to work on this issue.

**Comment by ritzvik** [comment]
> i want to work on this issue. May I?

Sure @fiterace . Have your way with the issue ;)

**Comment by ritzvik** [comment]
@fiterace Sorry for not giving you adequate time to take up the issue. Hope you would understand the urgency. 
@shreyasbapat PR has been put up addressing this. #217
