### ISSUE TITLE
Optimize functions in Metric module

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#213]
🐞 **Problem**
`return_cartesian` option in functions `calculate_trajectory()` and `calculate_trajectory_iterator()` in all three classes in `metric` module seem slow!! This becomes quite evident on running the tests.

This is because, on each iteration, values are being converted to ~astropy.unit Quantities and then passed to the coordinate module.

🎯 **Goal**
  - Speed 'em up.

💡 **Possible solutions**
  - Discuss the approach and then go ahead with a PR.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #213`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
Do you have any suggestion in mind?

**Comment by ritzvik** [comment]
> Do you have any suggestion in mind?

removing the decorator `astropy.units.quantity_input` from functions in `coordinates` module would work I guess.
Then there would be no need to convert them to astropy Quantities.
What do you think?

**Comment by shreyasbapat** [comment]
But won't that make us suffer from units issues?

**Comment by shreyasbapat** [comment]
When we talk about coordinates, units are necessary!

**Comment by ritzvik** [comment]
> When we talk about coordinates, units are necessary!

What do you suggest we do then???

**Comment by shreyasbapat** [comment]
> What do you suggest we do then???

Instead of having accuracy and precision with user friendliness at stake, we close this issue!

Also, we contribute to astropy units and boost their performance upstream!

**Comment by ritzvik** [comment]
> > What do you suggest we do then???
> 
> Instead of having accuracy and precision with user friendliness at stake, we close this issue!

Closing would not do the trick. Things have become slow by factor of 4x-5x.  What I suggest, we implement the conversions within the `if-else` condition for the time-being.
https://github.com/einsteinpy/einsteinpy/blob/master/src/einsteinpy/metric/kerr.py#L177-L193

**Comment by ritzvik** [comment]
@shreyasbapat Suggestions? 
![rgrr](https://user-images.githubusercontent.com/24695764/56976346-5f4f3580-6b90-11e9-875d-4cf0c26c5d10.jpg)

**Comment by shreyasbapat** [comment]
> Closing would not do the trick

I never said it would. I am just saying that, sacrificing usability for performance is not good. If you don't handle units well, you are not producing a software that can guarantee a good and accurate result. 

> What I suggest, we implement the conversions within the if-else condition for the time-being.

The actual users would never use it like that! Perhaps for playing around, it may seem fine. But we must be very clear with what the objective of the package is. You can either have usability or performance (useless to everyone)

**Comment by shreyasbapat** [comment]
And other points that I want to put forward:

1) Having if else in a core API is never suitable. Let it be slow. We will make it fast by making something to handle units. But as long as we are dependent on astropy (And I don't think we can code units better than what astropy already has! ), there is no point of crying about performance here. We should go and do as much possible to make astropy units fast! 

2) We have many more implications based on this. This is not a hackathon code that we can just add whatever we want. There has to be some structure to the code. And I am very much against of this idea of removing astropy units.

**Comment by shreyasbapat** [comment]
And other points that I want to put forward:

1) Having if else in a core API is never suitable. Let it be slow. We will make it fast by making something to handle units. But as long as we are dependent on astropy (And I don't think we can code units better than what astropy already has! ), there is no point of crying about performance here. We should go and do as much possible to make astropy units fast! 

2) We have many more implications based on this. This is not a hackathon code that we can just add whatever we want. There has to be some structure to the code. And I am very much against of this idea of removing astropy units.

**Comment by shreyasbapat** [comment]
If there is a bottleneck in the code, you try to make the neck wider, not remove it or bypass it!

**Comment by ritzvik** [comment]
> > > What do you suggest we do then???
> > 
> > 
> > Instead of having accuracy and precision with user friendliness at stake, we close this issue!
> 
> Closing would not do the trick. Things have become slow by factor of 4x-5x. What I suggest, we implement the conversions within the `if-else` condition for the time-being.
> https://github.com/einsteinpy/einsteinpy/blob/master/src/einsteinpy/metric/kerr.py#L177-L193

@shreyasbapat I believe you got me it wrong what I meant to say. I think we already came to an agreement not to remove astropy units. I was saying that what whatever code is inside the coordinates module for handling conversions, we can paste the same code within the functions in `metric` module, instead of creating objects. Maybe, give my comment a second read.

And my judgement says that we should let the issue remain open, and come back to it when the time is right as a common agreement regarding the solution can't be reached as of now. However, if you insist, the issue can be closed.

On a lighter note, you wrote the same comment twice :)

**Comment by shreyasbapat** [comment]
>  I was saying that what whatever code is inside the coordinates module for handling conversions, we can paste the same code within the functions in metric module, instead of creating objects.

Then that would increase the code redundancy :/

**Comment by shreyasbapat** [comment]
> On a lighter note, you wrote the same comment twice :)

Where :confused:

**Comment by ritzvik** [comment]
> > On a lighter note, you wrote the same comment twice :)
> 
> Where 😕

My bad, my browser rendered the same comment twice. Refreshed it 😄

**Comment by ritzvik** [comment]
> > I was saying that what whatever code is inside the coordinates module for handling conversions, we can paste the same code within the functions in metric module, instead of creating objects.
> 
> Then that would increase the code redundancy :/


> And my judgement says that we should let the issue remain open, and come back to it when the time is right as a common agreement regarding the solution can't be reached as of now. However, if you insist, the issue can be closed.
.

**Comment by ritzvik** [comment]
Duplicate Issue #286 , this should have been sorted out much earlier. Closing this one .
