### ISSUE TITLE
Variable in metric module not named aptly!

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#214]
🐞 **Problem**
In all three classes in `metric` module, within the functions `calculate_trajectory()` and `calculate_trajectory_iterator()`, a boolean variable named `singularity_reached` keeps track whether the particle has crossed the event horizon or not. Singularity means the center of black hole where the space-time curvature becomes infinite. So the variable name does not reflect its usage.

🎯 **Goal**

  - Think of a relevant name and make a PR.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #214`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Ankk98** [comment]
I would like to work on this beginner-friendly issue.

**Comment by ritzvik** [comment]
> I would like to work on this beginner-friendly issue.

Sure. Go ahead.
