### ISSUE TITLE
Change Navigation Bar style in docs

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#218]
🐞 **Problem**
The highlighted link is split in two lines, and there is no way to differentiate.
![30](https://user-images.githubusercontent.com/24695764/56868941-e7113480-6a16-11e9-923d-dd099e3f14bc.PNG)
See for yourself at http://docs.einsteinpy.org/en/latest/

🎯 **Goal**
  - Make the index bulleted.

💡 **Possible solutions**
  - Tinker in `docs/source/_static/custom.css`
  - Hint : 
    ```
    div.sphinxsidebar ul {.....}
    ```

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #218`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by fiterace** [comment]
hi @ritzvik I would like to work on this issue
