### ISSUE TITLE
handle DeprecationWarning in tests

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#221]
🐞 **Problem**
In all CI tests, `astropy.units` is raising `DeprecationWarning`.  
```
=============================== warnings summary ===============================
venv/lib/python3.6/site-packages/einsteinpy/utils/bl_coord_transforms.py:8
  /home/circleci/repo/venv/lib/python3.6/site-packages/einsteinpy/utils/bl_coord_transforms.py:8: PendingDeprecationWarning: This module will be deprecated in EinsteinPy v0.3.0. Please switch to `einsteinpy.coordinates`.
    PendingDeprecationWarning,

venv/lib/python3.6/site-packages/einsteinpy/utils/coord_transforms.py:8
  /home/circleci/repo/venv/lib/python3.6/site-packages/einsteinpy/utils/coord_transforms.py:8: PendingDeprecationWarning: This module will be deprecated in EinsteinPy v0.3.0. Please switch to `einsteinpy.coordinates`.
    PendingDeprecationWarning,

src/einsteinpy/tests/test_plotting/test_staticgeodesicplotter.py::test_plot_calls_draw_attractor_Manualscale
  /home/circleci/repo/venv/lib/python3.6/site-packages/astropy/units/quantity.py:855: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
    return super().__ne__(other)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
==================== 99 passed, 3 warnings in 60.34 seconds ====================
```

🎯 **Goal**
  - Fix it.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #221`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
It's okay! I guess it is the problem upstream. We *must* not suppress warnings in tests!

**Comment by ritzvik** [comment]
> It's okay! I guess it is the problem upstream. We _must_ not suppress warnings in tests!

The problem may be upstream. I was not indicating to suppress the warnings. Just wanna know and fix the cause. Again, the problem may be upstream.

**Comment by ritzvik** [comment]
The problem is not upstream. Problem is `astropy.units.quantity.Quatitity` object is compared with `int`.

In the function `test_plot_calls_draw_attractor_Manualscale()` replacing `!=` by `is not` would do the trick.
@shreyasbapat It's a good first issue ;)

**Comment by shakeabi** [comment]
@ritzvik I would like to work on this.

**Comment by rtanmay** [comment]
@shreyasbapat  @ritzvik  is this issue still open?

**Comment by shreyasbapat** [comment]
> @shreyasbapat @ritzvik is this issue still open?

Yes.

**Comment by ritzvik** [comment]
The warning no longer shows up, so closing the issue!
