### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by zeeshanahmad1** [einsteinpy/einsteinpy#226]
einsteinpy installtion command is not running on cmd..

**Comment by shreyasbapat** [comment]
Hi Zeeshan!

I am glad you tried installing EinsteinPy.
I would like to know more details.
What is your Operating System?
What command did you run?
What errors did you get?

Thanks
Shreyas

**Comment by shreyasbapat** [comment]
Hi @zeeshanahmad1 . Do you have any updates?

**Comment by shreyasbapat** [comment]
I am gonna close this issue due to lack of details, please comment on the closed issue / reopen the issue @zeeshanahmad1 if you still have any issues. :)
