### ISSUE TITLE
A new Kanban for EinsteinPy

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#231]
🐞 **Problem**
Related to #229 
As waffle.io is no longer with us, it's time for a replacement.

🎯 **Goal**
Get a new Kanban up & running.

💡 **Possible solutions**
https://stackshare.io/waffle-io/alternatives
See & inspect the alternatives.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #231`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
I think GitHub Projects must suffice our usecase for now. Closing this! We will reopen if needed!
