### ISSUE TITLE
Add more Bodies to the bodies module

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#234]
🐞 **Problem**

Currently, the bodies module only has 2 bodies. The list can be extended.

🎯 **Goal**

A better plotting experience

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by abhijeetmanhas** [comment]
I will work on it. I have created classes for moon, 7 other planets of solar system and Pluto. I will be adding mass and radius details. I have already done for Moon.

**Comment by SuyashSalampuria** [comment]
@shreyasbapat I would like to work on this issue .
Also, could you give details of what changes should I do to achieve this
