### ISSUE TITLE
Alternative to plotly for interactive plotting.

### ISSUE THREAD

**Issue by Varunvaruns9** [einsteinpy/einsteinpy#235]
🐞 **What bugs you?**

We wanted to add interactive plotting using Plotly as an alternative to matplotlib but there are some concerns regarding its use. Plotly seems to work well when used in a Jupyter notebook or with a web application but there is no satisfactory way of using it with the command line. We can either return an object with details about the plot or save the plot as an image or HTML file that can be viewed later. We need a good way to show the plots directly or look for an alternative.

**Comment by shreyasbapat** [comment]
https://matrix.to/#/!KXuIZXQfZbpAMwZnrm:matrix.org/$1560528462984755yvxmE:matrix.org?via=matrix.org&via=cadair.com&via=t2bot.io

Let's try out Bokeh?

**Comment by Varunvaruns9** [comment]
Bokeh seems to have the same problem as plotly, it is meant for displaying the results in a browser or notebook.

**Comment by shreyasbapat** [comment]
What are the other options available then?

**Comment by Varunvaruns9** [comment]
I was looking at Mayavi which requires VTK which would be an additional dependency. I still have to check if it is working well with Jupyter.

If this also doesn't work, we will have to go with either Plotly or stay on matplotlib.

**Comment by shreyasbapat** [comment]
No Mayavi :/

Ok, let's do one thing. Let's give user a chance to set the working
environment they are in. And then render the related plots?
How about this?
So by this approach we would go with plotly!

**Comment by Varunvaruns9** [comment]
Ok, then are we displaying the plot in a browser window when the code is run from the command line?

**Comment by shreyasbapat** [comment]
My idea is: 
If user is on shell, display matplotlib
If user is on notebook, display plotly

And of course give options to user. This is difficult but I think we can do it?

**Comment by Varunvaruns9** [comment]
This is possible but using separate libraries for them might confuse some
people due to different interfaces.

Matplotlib already has an interactive mode for notebook using '% matplotlib
notebook' so we can use it for both cases.
We can also use Plotly for both if you are fine with viewing the plot in a
browser window instead of a dedicated one like in matplotlib.

**Comment by Varunvaruns9** [comment]
@shreyasbapat Which approach should I finally start working on?

**Comment by shreyasbapat** [comment]
> Matplotlib already has an interactive mode for notebook using '% matplotlib
notebook' so we can use it for both cases.

That's nothing as compared to plotly

> We can also use Plotly for both if you are fine with viewing the plot in a
browser window instead of a dedicated one like in matplotlib.

We have to use matplotlib for plots to show in papers and books. :)

**Comment by shreyasbapat** [comment]
I guess, we are good with plotly for now!
