### ISSUE TITLE
Add a few special metrics in symbolic module

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#244]
🐞 **Problem**
Yes, I'm talking about Schwarzschild metric & possibly, Kerr metric.

💡 **Possible solutions**

  - These can be separate classes inheriting from `Metric` class, or just functions returning an object of the `Metric` class. Open to discussion

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
@shreyasbapat See the possible solutions and kindly put forward your opinion .

**Comment by OVSofia** [comment]
In my opinion the best option is the second (Just functions). 
But why they shouldn't be functions of the class ChristoffelSymbols(Tensor) ? (That's how I did it)

**Comment by ritzvik** [comment]
> In my opinion the best option is the second (Just functions).
> But why they shouldn't be functions of the class ChristoffelSymbols(Tensor) ? (That's how I did it)

That's what I was thinking, functions are best. They should be functions returning instances of `MetricTensor(Tensor)` and not be functions inside the class, so that the classes do not lose their generality.

**Comment by shreyasbapat** [comment]
What I think is, within the symbolic module, we can create a module for vacuum solutions and include it there!

**Comment by ritzvik** [comment]
> What I think is, within the symbolic module, we can create a module for vacuum solutions and include it there!

Like a new file `vaccum_metrics.py`
```
from .metric import MetricTensor

def SchwarzschildMetric():
    ...
    return MetricTensor(something, something)

def KerrMetric)():
    ...
    return MetricTensor(something, something)
```

How does this look??

**Comment by OVSofia** [comment]
> > What I think is, within the symbolic module, we can create a module for vacuum solutions and include it there!
> 
> Like a new file `vaccum_metrics.py`
> 
> ```
> from .metric import MetricTensor
> 
> def SchwarzschildMetric():
>     ...
>     return MetricTensor(something, something)
> 
> def KerrMetric():
>     ...
>     return MetricTensor(something, something)
> ```
> 
> How does this look??

Looks good!

**Comment by OVSofia** [comment]
I do it this this

**Comment by OVSofia** [comment]
I do it like this

**Comment by shreyasbapat** [comment]
I think we can still leave this open?

**Comment by ritzvik** [comment]
> I think we can still leave this open?

Yes please

**Comment by shreyasbapat** [comment]
Can you please add the list of special metrics which can be added here? Expectations from this issue!

**Comment by ritzvik** [comment]
> Can you please add the list of special metrics which can be added here? Expectations from this issue!

  - Kerr Metric
  - Kerr Newman Metric
 
Maybe, we can look for the database of exact solutions?

**Comment by shreyasbapat** [comment]
cc @cjayross 

Can you help us with the database?

**Comment by cjayross** [comment]
I can manage to incorporate a plethora of metrics with the overhaul I'm working on at the moment. I don't know how worthwhile it will be to declare a class for each and every exact solution to the field equations, so at the moment the plan is to have them be represented abstractly and simply allow a much easier interface for manipulating them into whatever it is you need from them.

**Comment by cjayross** [comment]
> cc @cjayross
> 
> Can you help us with the database?

Yes, I definitely can.
What I'm thinking is that you can represent each metric by having them defined within individual files with each following a template that sets one variable that stores the matrix representation of the metric and another to store the coordinate basis of said representation. This way, there is no longer any need for tediously having each of the hundreds of metrics be defined as their own individual class.

Beyond using templates, we could also organize the files themselves in directories labeled by their petrov classification (Type I, Type II, Type III, Type D, Type N, Type O). With the common metrics being accessible from __init__.py

**Comment by ritzvik** [comment]
Redundant issue!
Closing this in lieu of #309
