### ISSUE TITLE
Support indexing for Tensor object in symbolic module

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#245]
🐞 **Problem**
```
obj = Tensor(blah_blah)
obj[2,3]  # can't be done as of now
```
In short, `Tensor` object is not subscriptable.

🎯 **Goal**

  - Make them subscriptable

💡 **Possible solutions**

   - https://stackoverflow.com/questions/11469025/how-to-implement-a-subscriptable-class-in-python-subscriptable-class-not-subsc
  - Already `self.arr` is subscriptable, thanks to `sympy`. Use it's power for making this possible

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by OVSofia** [comment]
I start with this. I should have it, and the Metric Tensor class. ready for tomorrow night.

**Comment by ritzvik** [comment]
> I start with this. I should have it, and the Metric Tensor class. ready for tomorrow night.

Sure @OVSofia , don't take pressure. Have your way.

**Comment by shreyasbapat** [comment]
My god! great!
