### ISSUE TITLE
__str__ and __repr__ for Tensor Class

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#250]
🎯 **Goal**

  - Additions in `einsteinpy/symbolic/tensor.py`.
  - The heading of the issue is self-explanatory.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by OVSofia** [comment]
I'll start with this when I fix the mistakes of my last PR
