### ISSUE TITLE
Implement index raising and lowering in Tensors

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#256]
🐞 **Problem**
We have no way to know whether the Tensor has contravariant or covariant indices

🎯 **Goal**

The indices must be properly formatted in front of a symbol.

  - [x] Metric Tensor
  - [x] Christoffel Symbols
  - [x] Riemann Tensor
  - [x] Ricci Tensor
  - [x] Weyl Tensor

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
@spacetimeengineer , this idea blatantly plagiarized from spacetimeengine, we would surely give the due credits.
Thanks!

**Comment by shreyasbapat** [comment]
You can not bring any code from spacetimeengine. Its BSD 3 Claused and hence,  it is not possible for us to bring the code here.

**Comment by spacetimeengineer** [comment]
What recommendations do you have for me changing the license to accommodate your intentions? I am no expert on this subject but I really want you to take the code for whatever purpose necessary,

**Comment by ritzvik** [comment]
> What recommendations do you have for me changing the license to accommodate your intentions? I am no expert on this subject but I really want you to take the code for whatever purpose necessary,

Wow, thanks ! It's really generous of you. It would be good to have MIT license, as it's the most open of all. Anyways, don't take any action regarding this now. We would intimate you after coming to a conclusion about what to do. 

We welcome you to the community and you may join our chatroom https://riot.im/app/#/room/#einsteinpy:matrix.org

Again, thanks!!

**Comment by shreyasbapat** [comment]
> What recommendations do you have for me changing the license to accommodate your intentions? I am no expert on this subject but I really want you to take the code for whatever purpose necessary,

Hi @spacetimeengineer , I won't recommend you to change the licence. Its okay. I see that spacetimeengine and EinsteinPy are doing similar things. We know that already. So, is there any possible collaboration that can benefit the whole scientific community as a whole?

**Comment by spacetimeengineer** [comment]
I only added an MIT license just now. I kept BSD because Sympy uses it but apparently I am allowed to add a second license which SHOULD permit you to use it. I am not entirely sure how open source licensing works but I would really like to get it figured out.

**Comment by shreyasbapat** [comment]
@spacetimeengineer Can we discuss a few things somewhere? Some chat platform on which its wasy for you to communicate? :smiley:

**Comment by spacetimeengineer** [comment]
Of-course, I am working now but if you send me a link, I can revisit later.

**Comment by ritzvik** [comment]
> Of-course, I am working now but if you send me a link, I can revisit later.

If you are on Gitter then come say Hi here 😃 
https://gitter.im/EinsteinPy-Project/EinsteinPy

Our Riot and Gitter chatrooms are integrated

**Comment by shreyasbapat** [comment]
Closed in #278

**Comment by ritzvik** [comment]
@OVSofia , As evident from the checklist above, indices manipulation already works with some tensors. Kindly go through PR #278 thoroughly and try to understand the working. See the example http://docs.einsteinpy.org/en/latest/examples/Playing_with_Contravariant_and%20Covariant_Indices_in_Tensors(Symbolic).html . I'm assigning this to you, try to check the other two tick-boxes :)

**Comment by ritzvik** [comment]
@OVSofia , ricci tensor checked! :)
