### ISSUE TITLE
Integrate Sympy's Lambdify in EinsteinPy

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#263]
Our tensors should have the ability to represent arrays of numpy-like functions rather than sympy expressions

**Comment by ritzvik** [comment]
@OVSofia , search about sympy's lambdify. Sooner or later, you would have to do this 😄

**Comment by ritzvik** [comment]
@OVSofia , only a few days are left in the SOCIS timeframe, so can you start working on this?

**Comment by OVSofia** [comment]
> @OVSofia , only a few days are left in the SOCIS timeframe, so can you start working on this?

I was with KerrMetric and KerrNewmanMetric, but I can fix this first

**Comment by ritzvik** [comment]
> > @OVSofia , only a few days are left in the SOCIS timeframe, so can you start working on this?
> 
> I was with KerrMetric and KerrNewmanMetric, but I can fix this first

I have other plans for them. Let's work on this first!

**Comment by OVSofia** [comment]
@ritzvik @shreyasbapat I think this task is already (in the absence of being reviewed ) done. I have seen that issue #259 is missing. Do I start with that?
