### ISSUE TITLE
Docs not present for Ricci Tensor & Vacuum Metrics

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#267]
**Possible solutions**
  - Additions in `docs/source/api/symbolic/symbolic_index.rst`
  - New files `docs/source/api/symbolic/ricci.rst`, `docs/source/api/symbolic/vacuum_metric.rst`

  - Add `vacuum_metric` to `symbolic/__init__.py`

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by OVSofia** [comment]
Instead of "vacuum_metric.rst" vacuum_metrics.rst, right? (with S)

**Comment by OVSofia** [comment]
"Additions in docs/source/api/symbolic/symbolic_index.rst"
I do not add either einstein or stress_energy_momentum, since they still don't work. 
So, tell me if I have to add it

**Comment by OVSofia** [comment]
I could not link my last commit with this task, but it's done in it. 
Next time I will write the issue number in the commit to make sure

**Comment by ritzvik** [comment]
> Instead of "vacuum_metric.rst" vacuum_metrics.rst, right? (with S)

whatever you named the `.py` file


> "Additions in docs/source/api/symbolic/symbolic_index.rst"
> I do not add either einstein or stress_energy_momentum, since they still don't work.
> So, tell me if I have to add it

No, only add those which you have completed.

**Comment by shreyasbapat** [comment]
Fix this ASAP!

**Comment by OVSofia** [comment]
I think thath is already fixed.

**Comment by ritzvik** [comment]
> I think thath is already fixed.

Nopes.
I already told you to learn how to add documentation from PR #241 
You need to add new files in `docs/source/api/symbolic` and edit the index there.

**Comment by OVSofia** [comment]
That's what I think I've done

**Comment by OVSofia** [comment]
Create  ricci.rst:
Ricci Tensor Module
===================

This module contains the class for obtaining Ricci Tensor
related to a Metric belonging to any arbitrary space-time symbolically:

.. automodule:: einsteinpy.symbolic.ricci
    :members:

and vacuum_metrics.rst:
Vacuum Metrics Tensor Module
=============================

This module contains the definition Schwarzschild Metric
related to a Metric belonging to any arbitrary space-time symbolically:

.. automodule:: einsteinpy.symbolic.vacuum_metrics
    :members:


 in docs/source/api/symbolic


Its not this?

**Comment by ritzvik** [comment]
In `einsteinpy/symbolic/__init__.py`, you would also need to add the line `from vacuum_metrics import SchwarzschildMetric`. Remember `black` & `isort` OR `tox`.



> # Create ricci.rst:
> Ricci Tensor Module
> This module contains the class for obtaining Ricci Tensor
> related to a Metric belonging to any arbitrary space-time symbolically:
> 
> .. automodule:: einsteinpy.symbolic.ricci
> :members:
> 
> # and vacuum_metrics.rst:
> Vacuum Metrics Tensor Module
> This module contains the definition Schwarzschild Metric
> related to a Metric belonging to any arbitrary space-time symbolically:
> 
> .. automodule:: einsteinpy.symbolic.vacuum_metrics
> :members:
> 
> in docs/source/api/symbolic
> 
> Its not this?

Yes, add these, make a new PR with a new branch.

Also add:
  - `vacuum_metrics` and 
  - `ricci`

in `docs/source/api/symbolic/symbolic_index.rst`

**Comment by OVSofia** [comment]
I think I did all this when I did the push this morning, so I've done a PR of my commit to try to clarify this issue and finally close it :)

**Comment by OVSofia** [comment]
Just in case I've create a new branch
