### ISSUE TITLE
Huge Changes required in User Guide

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#271]
🐞 **Problem**
Significant API changes were carried out in #248

🎯 **Goal**
  - Make the User Guide consistent

💡 **Possible solutions**
  - File present here `docs/source/user_guide.rst`

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
Create a Pull Request ASAP
