### ISSUE TITLE
Idea: Add Geodesic to einsteinpy __init__

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#272]
🐞 **Problem**
There is no point in doing `from einsteinpy.geodesic import Geodesic`

🎯 **Goal**

Maybe, this looks better. `from einsteinpy import Geodesic`

💡 **Possible solutions**

Add to `src/einsteinpy/__init__.py`, `from .geodesic import Geodesic`.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
We can't add this to EinsteinPy's init for obvious reasons!

**Comment by ritzvik** [comment]
Numpy's init also doe this https://github.com/numpy/numpy/blob/master/numpy/__init__.py
