### ISSUE TITLE
Coordinate conversion inside plotting module not handled correctly

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#277]
🐞 **Problem**
Earlier, plotting was written with `Schwarzschild` in mind, which relies on Spherical Coordinates only. But as the plotting was extended for `Geodesic` object, it inherently deals with `Kerr` & `KerrNewman` also. The coordinate conversion inside `ScatterGeodesicPlotter` and `StaticGeodesicPlotter` is not taken care by coordinates module and the design assumes Spherical to Cartesian conversion by default(No BL taken in consideration). This leads to wrong calculations.

See https://github.com/einsteinpy/einsteinpy/blob/master/src/einsteinpy/plotting/geodesics/geodesics_scatter.py#L62-L63

🎯 **Goal**
  - Fix this

💡 **Possible solutions**
  - Maybe, use `return_cartesian = True` in `calculate_trajectory()` to get values directly in x,y,z form.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
@shreyasbapat @Varunvaruns9 , kind of an urgent problem!

**Comment by shreyasbapat** [comment]
Oh my my!

This needs a fix!

**Comment by shreyasbapat** [comment]
Closed in #274
