### ISSUE TITLE
Fix the docs :'( 

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#284]
🐞 **Problem**

https://docs.einsteinpy.org/en/latest/api/index.html

The graph clearly lacks the new modules :'( 

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
One more thing, `docs/source/examples/Playing_with_Contravariant_and Covariant_Indices_in_Tensors(Symbolic).ipynb` file name has one space instead of underscore (`_`).
Kindly fix this along the way!

**Comment by shreyasbapat** [comment]
That notebook was not even in example gallery. Please keep a note about it when you add new examples!
