### ISSUE TITLE
Create a backend(sort of) for coordinates module

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#286]
🐞 **Problem**
The coordinate conversions in EPY core functions like `calculate_trajectory()` in `metric` module is painfully slow. Part of the reason is we are first converting values into `astropy quantity` objects then passing them to `coordinates` module, that too tens of thousands of times.

Solving this would speed up plotting and trajectory calculation(4x-10x)

🎯 **Goal**

  - Create a backend module which wouldn't be exposed to users, but would be used by EPY core functionalities.
  - For example, in the `to_spherical()` function of `Cartesian` class in `src/einsteinpy/coordinates/core.py`, the computations are happening inside the function only. Maybe we can pass that computation to that backend module. And that same backend module can be used by `calculate_trajectory()`.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
I will do it personally!

**Comment by ritzvik** [comment]
> I will do it personally!

OK then.

**Comment by shreyasbapat** [comment]
Closed in https://github.com/einsteinpy/einsteinpy/commit/9ccf6d6341713409159d837b18737187e0aa7144
