### ISSUE TITLE
Extend support of Tensor Class(symbolic) to support scalars

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#288]
🐞 **Problem**
Scalars are also zero order tensors. The Tensor class currently supports 1st order tensors and above.

🎯 **Goal**

  - Make `Tensor` support scalars. This issue can also help in #287 .

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by OVSofia** [comment]
I'll handle this,  if that's all right
