### ISSUE TITLE
The Interactive Plots do not show up in notebook!

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#289]
🐞 **Problem**

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
Closed in #290

**Comment by ritzvik** [comment]
Still not showing up!
http://docs.einsteinpy.org/en/latest/examples/Visualizing_advance_of_perihelion_of_a_test_particle_in_Schwarzschild_space-time.html

**Comment by shreyasbapat** [comment]
Oghhhhhh!

**Comment by shreyasbapat** [comment]
From browser console!

```
Uncaught ReferenceError: requirejs is not defined
    at Visualizing_advance_of_perihelion_of_a_test_particle_in_Schwarzschild_space-time.html:322

Failed to load resource: net::ERR_NAME_RESOLUTION_FAILED

Failed to load resource: net::ERR_NAME_RESOLUTION_FAILED

```

**Comment by ritzvik** [comment]
I think I'm going to host plots online for this example, doing this in PR #291

**Comment by shreyasbapat** [comment]
No. We need to fix the cause of this issue. Not over up for it.

**Comment by ritzvik** [comment]
> No. We need to fix the cause of this issue. Not cover up for it.

Done in #291, we got injected JS script showing up on sphinx. Check the PR

**Comment by shreyasbapat** [comment]
Closed in https://github.com/einsteinpy/einsteinpy/commit/5df0f3b9e53a9c923b6d1c63c3b3d3c9fc4efe9f
