### ISSUE TITLE
Leverage Symmetry in Christoffel Symbols to improve the performance of symbolic module

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#299]
🐞 **Problem**
  - Christoffel Symbols are symmetric over 2nd and 3rd indices

🎯 **Goal**

  - Use this property to speed up it's calculation from metric tensor

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
@OVSofia as discussed, assigning this to you. Happy coding 😄

**Comment by OVSofia** [comment]
I've been looking it and I think the code is already based on the symmetry of the 2nd and 3rd indices because it uses this formula:
![image](https://user-images.githubusercontent.com/51050291/61814522-8bedb300-ae48-11e9-9bd3-3a09bd27d2b9.png)
`tmpvar += (matinv[i, n] / 2) * (
                    sympy.diff(mat[n, j], syms[k])
                    + sympy.diff(mat[n, k], syms[j])
                    - sympy.diff(mat[j, k], syms[n])`

Please, let me know if I am wrong!  >.<

**Comment by ritzvik** [comment]
cc @OVSofia 

```
        for t in range(dims ** 3):
            # i,j,k each goes from 0 to (dims-1)
            # hack for codeclimate. Could be done with 3 nested for loops
            k = t % dims
            j = (int(t / dims)) % (dims)
            i = (int(t / (dims ** 2))) % (dims)
            tmpvar = 0
            for n in range(dims):
                tmpvar += (matinv[i, n] / 2) * (
                    sympy.diff(mat[n, j], syms[k])
                    + sympy.diff(mat[n, k], syms[j])
                    - sympy.diff(mat[j, k], syms[n])
                )
            tmplist[i][j][k] = tmpvar
        return cls(tmplist, syms, config="ull", parent_metric=metric)
```
The current code looks like this
`j`,`k` are the symmetric indices. Currently `j` and `k` both run from `0` to `dims-1` independent of each other. However you can create conditions such that `k<=j` always and then you can use `tmplist[i][j][k] = tmplist[i][k][j] = tmpvar`. This would reduce the computation by half.
