### ISSUE TITLE
Add loads of predefined metrics in symbolic module

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#309]
🐞 **What bugs you?**
  - Have predefined metrics in *symbolic* module

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by kauii8school** [comment]
I'm about to submit a pull request adding in the "Barriola Vilekin" metric. There are plenty of readily available metrics at https://arxiv.org/pdf/0904.4184.pdf. I will be adding those in the next few days!

**Comment by ritzvik** [comment]
Reopening this.
This is gonna be a perpetual issue 😛

**Comment by obi-wan-shinobi** [comment]
I added the Reissner-Nordstorm Metric. Please review so that I can add more :)
