### ISSUE TITLE
Notebook example for StressEnergyMomentum Tensor and Schouten Tensor

### ISSUE THREAD

**Issue by OVSofia** [einsteinpy/einsteinpy#321]
🎯 **Goal**

 * Create jupyter notebook example for StressEnergyMomentum Tensor and Schouten Tensor

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
Leave it! I think there are enough examples. Let people figure out from documentation 🤣
