### ISSUE TITLE
Docs build failing, some problem in the symbolic constants module

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#324]
🐞 **Problem**
CircleCI docs build is failing. There is some problem in `einsteinpy.symbolic.constants`.

Also, it is weird that an example code-block is appearing out of nowhere.
See http://docs.einsteinpy.org/en/latest/api/symbolic/constants.html

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

@einsteinpy/documentation-team

**Comment by shreyasbapat** [comment]
I understand the issue! On it!
