### ISSUE TITLE
Testing error in virtual environment

### ISSUE THREAD

**Issue by rdisipio** [einsteinpy/einsteinpy#326]
Hi,

  I'm installing EinsteinPy 0.2.0 on my MacOsX laptop. This is the sequence of instructions I've run:

```
virtualenv -p /usr/local/bin/python3 gr
source gr/bin/activate
pip3 install einsteinpy
```

If I try to execute the testing suite, it complains about a missing package. So I added:
```
pip3 install pytest
```

But again, if I do:
```
python
>>> import einsteinpy.testing
>>> einsteinpy.testing.test()
```

I get the following output:

```
================================================================= test session starts ==================================================================
platform darwin -- Python 3.7.3, pytest-5.1.1, py-1.8.0, pluggy-0.12.0
rootdir: /Users/disipio/university/development/janus
collected 121 items / 1 errors / 120 selected                                                                                                          

======================================================================== ERRORS ========================================================================
__________________________ ERROR collecting gr/lib/python3.7/site-packages/einsteinpy/tests/test_plotting/test_interactive.py __________________________
ImportError while importing test module '/Users/disipio/university/development/janus/gr/lib/python3.7/site-packages/einsteinpy/tests/test_plotting/test_interactive.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gr/lib/python3.7/site-packages/einsteinpy/tests/test_plotting/test_interactive.py:7: in <module>
    from plotly.graph_objs import FigureWidget
E   ImportError: cannot import name 'FigureWidget' from 'plotly.graph_objs' (/Users/disipio/university/development/janus/gr/lib/python3.7/site-packages/plotly/graph_objs/__init__.py)
```

I checked that plotly is installed.

**Comment by ritzvik** [comment]
@shreyasbapat

**Comment by shreyasbapat** [comment]
HI @rdisipio ,

I am really sorry. For FigureWidget to run properly, one needs to have `ipywidgets` installed. Which your virtual environment lacks. I could easily reproduce the issue. And this issue will be gone in `0.2.1` release. So a quick fix would be: 

```
pip install ipywidgets
```

**Comment by rdisipio** [comment]
Thanks! It worked now. Perhaps you want to make this more clear in the documentation?

r.

**Comment by shreyasbapat** [comment]
> Thanks! It worked now. Perhaps you want to make this more clear in the documentation?

Definitely, we are working on the performance of some parts right now, and there is no need of ipywidgets if you work in the dev version. So, once we release the 0.2.1, these issues must go away!

Now, as we can't really touch the older versions, IDK how to fix the documentation of the 0.2.0 :/ 

Any ideas @ritzvik ?

**Comment by shreyasbapat** [comment]
I am closing this as of now!

**Comment by ritzvik** [comment]
> > Thanks! It worked now. Perhaps you want to make this more clear in the documentation?
> 
> Definitely, we are working on the performance of some parts right now, and there is no need of ipywidgets if you work in the dev version. So, once we release the 0.2.1, these issues must go away!
> 
> Now, as we can't really touch the older versions, IDK how to fix the documentation of the 0.2.0 :/
> 
> Any ideas @ritzvik ?

I would make a PR to `0.2.x` branch 
  - make the change in `README.rst`. 

Anywhere else, should I make the change? @shreyasbapat

**Comment by shreyasbapat** [comment]
NO, that does not make sense! That PR will be merged in 0.2.1 when we will not be facing this problem.

**Comment by shreyasbapat** [comment]
Okay, me and @Varunvaruns9  will handle it

**Comment by ritzvik** [comment]
> Okay, me and @Varunvaruns9 will handle it

As you wish!! 🎵
