### ISSUE TITLE
Add a donation button on documentation

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#341]
🐞 **Problem**

The documentation at https://docs.einsteinpy.org lacks a donation button. :D

Just for hacktoberfest !!

Documentation is in docs/source :D

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by carlosolimpio** [comment]
hey @shreyasbapat, I'd like to make it

**Comment by shreyasbapat** [comment]
Hi Carlos! Sure go ahead.

**Comment by carlosolimpio** [comment]
Shreyas, I'm getting this error message while trying to `make html`:
```
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.6.7

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/config.py", line 157, in __init__
    execfile_(filename, config)
  File "/usr/lib/python2.7/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/usr/lib/python2.7/dist-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 6, in <module>
    import einsteinpy
ImportError: No module named einsteinpy

Makefile:53: recipe for target 'html' failed
make: *** [html] Error 1

```

**Comment by xtealer00** [comment]
Gonna be workin' on it.

**Comment by ritzvik** [comment]
@carlosolimpio you may need to install einsteinpy development version
http://docs.einsteinpy.org/en/latest/getting_started.html#development-version

**Comment by shreyasbapat** [comment]
Solved in https://github.com/einsteinpy/einsteinpy/commit/6919b3714792d859db7d053681c7c3ca108a092f
