### ISSUE TITLE
Add schwarzschild metric to predefined tensors

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#342]
🐞 **Problem**
Schwarzschild solution, the most commonly used metric in GR in not present in predefined metrics.

💡 **Possible solutions**

  - https://en.wikipedia.org/wiki/Schwarzschild_metric#The_Schwarzschild_metric
  - The metric can already be found in many jupyter examples/tests
  - Add a new file in `einsteinpy/symbolic/predefined`

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by longdead-ai** [comment]
I would like to take a look at this.

**Comment by shreyasbapat** [comment]
Hi @longdead-ai , sure go ahead!

**Comment by abhijeetmanhas** [comment]
There is already one function named `SwarzschildMetric`  defined at `einsteinpy/tests/test_symbolic/test_vacuum_metrics.py` but it returns only Metric Tensor of symbols. And one more file  at `metric/swarzschild.py` which can calculate trajectories corresponding to geodesics. What should be the functionalites of 'predefined/swarchzschild' @ritzvik ? Solving it in various coordinate systems?

**Comment by shreyasbapat** [comment]
Here we are talking about the symbolic module :)

**Comment by ritzvik** [comment]
> There is already one function named `SwarzschildMetric` defined at `einsteinpy/tests/test_symbolic/test_vacuum_metrics.py` but it returns only Metric Tensor of symbols. And one more file at `metric/swarzschild.py` which can calculate trajectories corresponding to geodesics. What should be the functionalites of 'predefined/swarchzschild' @ritzvik ? Solving it in various coordinate systems?

@abhijeetmanhas As said by @shreyasbapat , this issue is regarding symbolic module. Kindly see the labels :)
