### ISSUE TITLE
Couldn't not run Coordinate Conversion example / tutorial

### ISSUE THREAD

**Issue by xavdr** [einsteinpy/einsteinpy#343]
🐞 **Problem**

Can't run Coordinate Conversion example with message RuntimeWarning: invalid value encountered in double_scalars in coordinates/utils.py:85

So when calling `pos_vec.to_bl` at python example beginning  
```
a = 0.5 * u.km
pos_vec = Cartesian(.265003774 * u.km, -153.000000e-03 * u.km,  0 * u.km) 
bl_pos = pos_vec.to_bl(a)
print(bl_pos)
...
```

it execute `cartesian_to_bl_novel(x, y, z, a)` in coordinates/utils.py
```
w = (x ** 2 + y ** 2 + z ** 2) - (a ** 2)
r = np.sqrt(0.5 * (w + np.sqrt((w ** 2) + (4 * (a ** 2) * (z ** 2)))))
theta = np.arccos(z / r)
...
```
First line seems resulted as
```
w = 265.003774 ** 2 + (-153.0) ** 2 + 0.0 ** 2 - 500.0 ** 2 = -156363.99976575692
```
With `z = 0` second line reduces to `r = np.sqrt(0.5 * (w + np.sqrt((w ** 2) )))`. Obviously with any negative `w` it result to `r = 0` which leads to zero division in `theta = np.arccos(z / r)`

**Comment by xavdr** [comment]
Thank you, @shreyasbapat . For me is way to compare with previous releases. I'm not yet very specialist on Relativity Theory, in fact I found this nice project accidentally as way to approach classic equations and Math symbolic.

**Comment by Varunvaruns9** [comment]
Hi @xavdr, Thanks for reporting. @shreyasbapat What should be the result if `w` is negative?

**Comment by shreyasbapat** [comment]
I think, mathematically it's correct. So until we verify that, raise an error saying coordinate conversation not possible. And maybe open an issue linking the line to verify. I am short on time these days, so this might be a workaround

**Comment by shreyasbapat** [comment]
I guess this one is fixed in #351

**Comment by shreyasbapat** [comment]
Or not?

**Comment by ritzvik** [comment]
Singularity in a Kerr space (BL coordinates) is a ring like area, unlike in Schwarzcshild, where singularity is just a point. The Cartesian (pseudo-Cartesian, anyways) are maybe, describing a point inside that point. And therefore, this problem is arising. 

At some point down the line, we can raise an exception or warning, but by no means, this is a bug.

It's best to close this for now.
