### ISSUE TITLE
Installation instructions does not specify lower bound on Ubuntu version and pip install method

### ISSUE THREAD

**Issue by Ojaswy** [einsteinpy/einsteinpy#350]
🐞 **Problem**
The Installation process mentioned in the Readme file does not work for Ubuntu/Debian.

The command there being - $ sudo apt install python3-einsteinpy
which gives an installation error.

pip install einsteinpy works instead.

AND
The link given under the Installation sub heading - Guide for alternative installation methods is obsolete.

📋  **Steps to solve the problem**

The ReadMe file requires an Updation. I can create a PR if it's okay.

**Comment by shreyasbapat** [comment]
Hi @Ojaswy 

Which version of Ubuntu are you using?

**Comment by Ojaswy** [comment]
18.04

**Comment by ritzvik** [comment]
> The link given under the Installation sub heading - Guide for alternative installation methods is obsolete.


Yes @Ojaswy ! Thanks for pointing out. Kindly go ahead and update it. Sorry for the delay.

**Comment by shreyasbapat** [comment]
No. Don't update it. I will check it. We will get it to work :)

**Comment by shreyasbapat** [comment]
Right, and I actually forgot to mention. We included it in Ubuntu from 19.10 so, obviously it won't work in 18.04. 

We are already running towards a latest LTS i.e. 20.04 so we need not worry
