### ISSUE TITLE
Sympy 1.5 Compatiliblity 

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#356]
🐞 **Problem**
As evident from PR #353 , EPY `v0.2.1` has become incompatible with latest versions of sympy(`1.5`).
As the problem is fixed, maybe we can release EPY `v0.2.2` ?

@shreyasbapat

**Comment by shreyasbapat** [comment]
I will work on this asap

**Comment by shreyasbapat** [comment]
No Questions required
