### ISSUE TITLE
Support Python 3.8 

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#358]
🐞 **Problem**

Form version 0.3.0, EinsteinPy should be tested on Python 3.8 also! 

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
@ritzvik It was assigned to me always

**Comment by ritzvik** [comment]
> @ritzvik It was assigned to me always

Didn't see. Anyway, thought lets close issues one by one!
