### ISSUE TITLE
Simulation of orbits - Animations

### ISSUE THREAD

**Issue by spino17** [einsteinpy/einsteinpy#36]
Simulating orbits with coordinate time running and correspondingly plot radial and angular coordinates and showing plots in animation format

**Comment by shreyasbapat** [comment]
Baiscally we want animations right?

**Comment by Varunvaruns9** [comment]
I would like to work on this.

**Comment by shreyasbapat** [comment]
First Animation Done :) 
Scatter Plotter animated in #177

**Comment by parkerashlan** [comment]
I was wondering if there is any more work that needs to be done on this issue? I would be interested in working on simulations of orbits.

**Comment by ritzvik** [comment]
> I was wondering if there is any more work that needs to be done on this issue? I would be interested in working on simulations of orbits.

Sorry for the delay in getting back to you. There is already some work done regarding this issue and there is not much clarity about what is to be done. 
Could you have a look at #450 , see if that interests you as it is a good starting point into the project.
