### ISSUE TITLE
Add Kerr and Kerr-Newman metric in Boyer-Lindquist coordinates to predefined metrics

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#360]
🐞 **Problem**
`symbolic/predefined/vacuum_solutions.py` needs Kerr and Kerr-Newman Metrics. Implement them similar to already implemented `Schwarzschild()` in the same file.

💡 **Possible solutions**

  - [x] Kerr (c737c8b)
  - [ ] Kerr Newman

The metrics can be found be simple search on wikipedia. Also implementation can be found in `utils/kerr_utils.py` and `utils/kerrnewman_utils.py`

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by sagnik-chatterjee** [comment]
Can I take up this issue ?

**Comment by ritzvik** [comment]
Try this one.

Regards,
Ritwik

**Comment by gimseng** [comment]
Hi I am interested in helping with this issue, but i am new to git and open source contribution. If its alright, could I take this issue? My background is in theoretical physics (GR), so I understand the symbolic/analytic side of the problem, but just wanted to learn and apply git and python codings. I am reading through the developer guide and the git intro at the moment, so I am hoping to deal with an actual issue ticket to apply my learning.

**Comment by ritzvik** [comment]
Sure @gimseng ! Take up the issue whenever you are comfortable. Ask us when you are stuck. 

Also, kindly join our community Chatroom on Riot.
https://riot.im/app/#/room/%23einsteinpy:matrix.org

**Comment by gimseng** [comment]
Thanks I will tackle this. If I understand it correctly, the Kerr one has been updated, so I just need to include the charge (Kerr-Newman) appropriately.

**Comment by ritzvik** [comment]
Yups. That’s correct 

Regards,
Ritwik

**Comment by gimseng** [comment]
Thanks! I am almost done now, but have two questions:

1. I need a new constant "eps0" (electric constant or permittivity of free space). I defaulted it to "constants.eps0", could somehow help me to find where in the codes should I update/add this values? 

2. I needed 'pi', do we do math.pi or its defined as constants.pi or something?

Sorry to ask trivial questions, since I am new to EinsteinPy, and I thought maybe I could use the opportunities to ask questions on this discussion area. Thanks !

**Comment by gimseng** [comment]
Nvm, I figured them out, will do a pull request.

**Comment by ritzvik** [comment]
Closed via #427
