### ISSUE TITLE
Make coordinate objects subscriptable

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#366]
🐞 **Problem**

We can't do a[0] with the coordinates right now, which is very intuitive. Thanks to @shilpi1958 , we know what needs to be done!
🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Raahul-Singh** [comment]
Would implementing `__getitem__` suffice?

**Comment by shreyasbapat** [comment]
I guess, for now? Maybe yes
