### ISSUE TITLE
Frame Dragging Example breaks on New plotting code

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#367]
🐞 **Problem**

Fix the scaling on y axis :/ 

![newplot (1)](https://user-images.githubusercontent.com/24257914/72183374-de7d5480-3413-11ea-87eb-4f36201a725b.png)

See the issue. The plot shoild have been like this: 

![download](https://user-images.githubusercontent.com/24257914/72183403-efc66100-3413-11ea-9e1a-a813287c3359.png)

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
It would break. See the scaling on the old and new y-axis.

**Comment by shreyasbapat** [comment]
Oh :/ Didn't pay attention there lol

**Comment by ritzvik** [comment]
Close this ? @shreyasbapat

**Comment by ritzvik** [comment]
> Close this ? @shreyasbapat

You edited the description, I didn't see. Maybe edit the issue title also?

**Comment by shreyasbapat** [comment]
No, the title is consistent. See this: 
![Screenshot from 2020-01-15 17-56-42](https://user-images.githubusercontent.com/24257914/72433955-7edeca80-37c0-11ea-9e54-46a7147108ef.png)

I am investigating the scaling in both the plotting codes.
This is a big issue since, we are not able to deal with interactive plots so well.

**Comment by ritzvik** [comment]
We would need atleast the matplotlib code to work correctly to include the plots in EPY paper. Can we raise it to urgent status, @shreyasbapat ?
Also this needs to sorted before `0.2.2`

https://gist.github.com/ritzvik/9271334525e5e1044ceb9bba7b88143c

**Comment by shreyasbapat** [comment]
I am really on it. Lot of things to do. Will get it sorted asap

_______________________________________
This email is sent from a smartphone. Please ignore grammatical mistakes
and typographical errors.
_______________________________________

**Comment by ritzvik** [comment]
I finally pushed myself to dive into the geodesic plotting codebase, and I would start off by saying that the way, `GeodesicPlotter` does switching is ingenious.

Now coming to the issue, scaling is set to one in both the static and interactive 2D plotter, which does not suffice for this case.

https://github.com/einsteinpy/einsteinpy/blob/5a2b0b0967fd40dc4d46e7c855a566bbd9833ee3/src/einsteinpy/plotting/geodesics/static.py#L35-L36

`scaleanchor` in this case,

https://github.com/einsteinpy/einsteinpy/blob/5a2b0b0967fd40dc4d46e7c855a566bbd9833ee3/src/einsteinpy/plotting/geodesics/interactive.py#L24-L28 

Now what I saw is `_draw_attractor` can handle only cases where the aspect ratio is ~1, and most probably it is the reason behind setting the aspect ratios to 1. **So what I propose is we simply mark a point in the place of attractor for this release, and let aspect ratios to be auto**. 



🐞  **Now coming to another bug I discovered in `_set_scaling`**,

https://github.com/einsteinpy/einsteinpy/blob/5a2b0b0967fd40dc4d46e7c855a566bbd9833ee3/src/einsteinpy/plotting/geodesics/static.py#L75-L83

This is where it gets called from.

https://github.com/einsteinpy/einsteinpy/blob/5a2b0b0967fd40dc4d46e7c855a566bbd9833ee3/src/einsteinpy/plotting/geodesics/static.py#L104-L110

Now let's suppose a case where `min(x) = 100` and `max(x) = 120`. Then the x axis in the plot would get set in between `-20` and `20`, and we would not able to see the plot.

@shreyasbapat , if the last issue looks credible, kindly open an issue.

**Comment by ritzvik** [comment]
Also I found some redundancies like,

https://github.com/einsteinpy/einsteinpy/blob/5a2b0b0967fd40dc4d46e7c855a566bbd9833ee3/src/einsteinpy/plotting/geodesics/static.py#L96-L99

https://github.com/einsteinpy/einsteinpy/blob/5a2b0b0967fd40dc4d46e7c855a566bbd9833ee3/src/einsteinpy/plotting/geodesics/interactive.py#L84-L86

`geodesic.trajectory` already returns `np` array and there is no need to convert again. This just makes the codebase slow

**Comment by shreyasbapat** [comment]
I am in process of looking into this.

_______________________________________
This email is sent from a smartphone. Please ignore grammatical mistakes
and typographical errors.
_______________________________________

**Comment by ritzvik** [comment]
@shreyasbapat , Did you look at the `_set_scaling` bug, I mentioned in here https://github.com/einsteinpy/einsteinpy/issues/367#issuecomment-576871961 ?

**Comment by JeS24** [comment]
@shreyasbapat @ritzvik Is this issue fixed? After the changes in #512, even the abnormal sideways movement is absent. Compare these:
***BEFORE***
![image](https://user-images.githubusercontent.com/31299799/85221729-e9311200-b3d3-11ea-96a8-d0862c540c35.png)


***AFTER***
![image](https://user-images.githubusercontent.com/31299799/85221722-df0f1380-b3d3-11ea-95c7-95560bec02f4.png)

**Comment by shreyasbapat** [comment]
Nope

**Comment by JeS24** [comment]
This should be a redundant issue now, no? @shreyasbapat

**Comment by shreyasbapat** [comment]
The problem is that it breaks on the new plotting code. The plotly one!
