### ISSUE TITLE
Update Appveyor Badge

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#373]
🐞 **Problem**
The appveyor badge turns red whenever a build in any PR is failing. We don't want appveyor badge to reflect any PR's status, but it should report only `master` branch's status.

What I mean is this : 
![10](https://user-images.githubusercontent.com/24695764/72500358-4a1f5180-385a-11ea-9107-3b0599299b3c.png)

🎯 **Goal**

Update the badge in `README.rst`

💡 **Possible solutions**

Take a look at [shields](https://shields.io/)

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by vineetg3** [comment]
Working on this.

**Comment by vineetg3** [comment]
Do the other continuous integration services show the same problem?

**Comment by ritzvik** [comment]
No they don’t. It’s specific to appveyor 

Regards,
Ritwik
