### ISSUE TITLE
Implement a "find" function for searching metrics within predefined metrics

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#376]
🐞 **Problem**
Few predefined metrics are already there in `symbolic/predefined` module and a lot more is yet to come. We can't expect the user to know each of the instances nor can we force him to look for the documentation everytime. Therefore a `find` function is required in which user can input a string and a list of possible metrics can be returned. 

🎯 **Goal**

Strategize how to implement this and get started with a PR. Maybe discuss here first?

💡 **Possible solutions**

We can check if the searched term is a substring of the function name or function docstring.
  - Function name can be returned as a string by `function.__name__`
  - Docstring can be returned as a string by `function.__doc__`

📤  **Expected Output**

For example, `find("sitter")` should return something like this : `['DeSitter', 'AntiDeSitter', 'AntiDeSitterStatic']`

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
I see where this is coming from :p

**Comment by k-pratyush** [comment]
Hey! I would like to work on this issue. Where do I implement this function?

**Comment by ritzvik** [comment]
> Hey! I would like to work on this issue. Where do I implement this function?

Make a file `find.py` inside the predefined directory.

Thanks for taking this up @k-pratyush
