### ISSUE TITLE
Fix-up imports within coordinates module

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#377]
🐞 **Problem**
[PEP8](https://www.python.org/dev/peps/pep-0008/#id23) recommends absolute imports and most of einsteinpy abides by it, exception being the `coordinates` module.

🎯 **Goal**

  - Identify the relative imports and fix them up.

💡 **Possible solutions**

  - To get an inkling about what I am saying, see any other module within einsteinpy, (`symbolic` or `metric`)

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by rohitsanj** [comment]
working on this 👍
