### ISSUE TITLE
Increase code coverage across different modules (easy ones)

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#378]
🐞 **Problem**
The goal is 100% code coverage. It's not a very realistic goal because sometimes we lack the knowledge to do so. But I am listing some of the parts, where coverage can be increased easily. 

🎯 **Goal**

Try to target these files. The lines untested would be marked red [here](https://codecov.io/gh/einsteinpy/einsteinpy/tree/master/src/einsteinpy).
  - [x] `coordinates/core.py` (#394)
  - [x] `ijit.py` (#397)
  - [x] `symbolic/vector.py`
  - [x] `symbolic/tensor.py`
  - [x] `plotting/hypersurface/core.py`
  - [x] `plotting/rays/shadow.py`
  - [x] `rays/shadow.py`

💡 **Possible solutions**

  - [What is coverage](https://confluence.atlassian.com/clover/about-code-coverage-71599496.html)
  - tests are present in `src\einsteinpy\tests\test_<module name>\test_<file name>`

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

@shreyasbapat if possible, add some more!

**Comment by Bhavam** [comment]
Working on this , will create PR soon.

**Comment by Bhavam** [comment]
Hey i'm still taking a bit too much time on it , im currently creating tests for coordinates/core if anyone wants to work on the other files please go ahead.

**Comment by Bhavam** [comment]
Also @shreyasbapat and @ritzvik  i fail to find a test module for coordinates/core file should i make one or insert my tests in an existing test module for coordinates.
Thanks again.

**Comment by ritzvik** [comment]
> Hey i'm still taking a bit too much time on it , im currently creating tests for coordinates/core if anyone wants to work on the other files please go ahead.

Open a PR with whatever you have, we'll refine it over there.



> Also @shreyasbapat and @ritzvik i fail to find a test module for coordinates/core file should i make one or insert my tests in an existing test module for coordinates.
> Thanks again.

Put them in `test_coordinates/tests_coord_transform.py`.

**Comment by Bhavam** [comment]
Thanks, ill do that then.

**Comment by mightomi** [comment]
I like to work on this issue if its available

**Comment by ritzvik** [comment]
> I like to work on this issue if its available

you can see that two modules are not fully covered as mentioned above. Take em up :)

**Comment by yashgurbani** [comment]
Hi, is this issue still open?

**Comment by ritzvik** [comment]
> Hi, is this issue still open?

Nah, taken and solved :(
