### ISSUE TITLE
Fix Docstrings in Geodesic Module

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#379]
🐞 **Problem**

The docstrings in src/einsteinpy/geodesic.py is missing.
It will be great to have a good documentation of the module.

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by nimeshvashistha** [comment]
Hi, can i work on this issue?
