### ISSUE TITLE
Implement "kerr" Metric

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#38]
Calculating the geodesics of rotating charged black holes (kerr geometry). It can be thought as a generalisation of Schwarzschild geometry. 

Idea :bulb: : We can create a parent class for `Schwarzschild` if that's possible.

**Comment by shreyasbapat** [comment]
@ritzvik Might complete kerr null geodesics soon!

**Comment by ritzvik** [comment]
time-like geodesics for Kerr Done!. Next stop : Kerr null geodesics

**Comment by ritzvik** [comment]
@shreyasbapat close this!

**Comment by shreyasbapat** [comment]
Closed in #101
