### ISSUE TITLE
Add __repr__ and __str__ for Geodesic Class

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#380]
🐞 **Problem**

The Geodesic class is missing these methods. More can be discusses in comments.

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Bhavam** [comment]
Hi this is Bhavam from the Pydata-devsprint from manipal , i'm currrently working on this issue and would like to know whether the format for the __str__ method would be okay with parameter like

return 'Geodesic (body='+self.body etc etc

**Comment by shreyasbapat** [comment]
I guess, create a PR and we will see what to do with it :) 
Works?

**Comment by Bhavam** [comment]
Yes sure thanks  , ill create a PR in a bit so you can review it.
