### ISSUE TITLE
Fix Grammatical issues in Code of Conduct and add it in docs

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#381]
🐞 **Problem**

The language in the COC is flawed.

```
 We will take action when members of our community violate this code such as contacting einsteinpy.project@gmail.com (all emails sent to this address will be treated with the strictest confidence) or talking privately with the person.
```

🎯 **Goal**

Fix it,

And add the COC to the documentation as well.

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ShamanthNyk** [comment]
I would like to work on this isssue

**Comment by ritzvik** [comment]
Great! Please go ahead.

Regards,
Ritwik

**Comment by ShamanthNyk** [comment]
So I will need to change the flaw mistake in the above sentence and then put in the docs right?

**Comment by ShamanthNyk** [comment]
So I will need to correct the mistake in the above sentence and then add it to the docs right?

**Comment by shreyasbapat** [comment]
Yes. This one will be here anyways. You just have to make sure that it appears in docs.einsteinpy.org/some_url as well

**Comment by smritisingh26** [comment]
Hey! Is this issue still open? If so, I’d like to take it up!

**Comment by ritzvik** [comment]
> Hey! Is this issue still open? If so, I’d like to take it up!

@smritisingh26 , @ShamanthNyk already took this up and a PR is underway, I'm afraid. Try to go for #379 , #378 or #360 .

**Comment by shreyasbapat** [comment]
Yes, @smritisingh26 I recommend you to take up #379 . Its a good starting point, and we need it before our release! :)

**Comment by smritisingh26** [comment]
> Yes, @smritisingh26 I recommend you to take up #379 . Its a good starting point, and we need it before our release! :)

Okay Shreyas! Thanks, I'll look into it!
