### ISSUE TITLE
API Docs for plotting module is incomplete!

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#384]
🐞 **Problem**

The API Docs for plotting module is incomplete and old. 
🎯 **Goal**
Update it

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by nimeshvashistha** [comment]
I'd like to take this issue up

**Comment by shreyasbapat** [comment]
Sure!

_______________________________________
This email is sent from a smartphone. Please ignore grammatical mistakes
and typographical errors.
_______________________________________

**Comment by shreyasbapat** [comment]
@nimeshvashistha See this https://docs.einsteinpy.org/en/latest/api/plotting/plotting_index.html

We lack the basic plotting API Documentation there. We have documentation for `senile`. But as the name suggests, it is anyways dead code!

**Comment by shreyasbapat** [comment]
I am taking this up!
