### ISSUE TITLE
Include additions of #385 in example notebooks

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#389]
🐞 **Problem**
With #385 , @k-pratyush closed #376 . We don't have an example jupyter notebook for the same.

🎯 **Goal**

Showcase this functionality in the already existing notebook for `predefined` sub-module, in `docs/source/examples/Predefined Metrics in Symbolic Module.ipynb`. View the notebook [here](https://docs.einsteinpy.org/en/latest/jupyter.html)

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Fixes #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by k-pratyush** [comment]
Can I do this?
@shreyasbapat @ritzvik

**Comment by ritzvik** [comment]
It’s yours!

Regards,
Ritwik
