### ISSUE TITLE
[No Issue]

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#395]
🎯 **Goal**

We can include an easter egg in the code somewhere!

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
I guess, for the sake of our paper, we will be directly releasing `0.3.0`. So, yeah we can do that!

**Comment by ritzvik** [comment]
> I guess, for the sake of our paper, we will be directly releasing `0.3.0`. So, yeah we can do that!

This issue's on me! I've a few ideas!

**Comment by ritzvik** [comment]
> I guess, for the sake of our paper, we will be directly releasing `0.3.0`. So, yeah we can do that!

If anything new like `null` can be added, then only `0.3.0` is justifiable, in my view. Otherwise, `0.2.2` is apt.
