### ISSUE TITLE
Add a 7th or 8th order ODE Solver

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#40]
Resources are available on internet. Also, they can be shared later on this thread.

**Comment by sagnik-chatterjee** [comment]
Can i try it with a scipy , with using function DOP853 ..a eightth order runge-kunta ode solver ?

**Comment by ritzvik** [comment]
I guess you should try out #360 first, then dive into deeper, not so good first issues. If you wanna go for it, be my guest :)

Regards,
Ritwik

**Comment by shreyasbapat** [comment]
Truly, I agree with @ritzvik .
If you feel you know things about ODEs. You are welcome to take this up. Otherwise it's not a good first issue

**Comment by SuyashSalampuria** [comment]
@shreyasbapat This seems interesting to me
Shall I try this one

**Comment by shreyasbapat** [comment]
Sure, let's first discuss the whole problem somewhere. And then you can proceed!

**Comment by JeS24** [comment]
Some related literature:
* https://arxiv.org/pdf/2010.02237.pdf
* https://www.unige.ch/~hairer/poly_geoint/week2.pdf
