### ISSUE TITLE
Consider replacing np.moveaxis with sympy permutedims

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#401]
🐞 **Problem**
Currently, to permute dimensions in a tensor, we first convert it to numpy object, apply `np.moveaxis` and then revert back to sympy `Array`.

The instances are :

https://github.com/einsteinpy/einsteinpy/blob/dfc3bc281e296adbaa486e1f5e5f24fc02adeac3/src/einsteinpy/symbolic/tensor.py#L55-L61

https://github.com/einsteinpy/einsteinpy/blob/dfc3bc281e296adbaa486e1f5e5f24fc02adeac3/src/einsteinpy/symbolic/tensor.py#L363-L369

💡 **Possible solutions**

As of sympy > `1.4`, a new function [`permutedims`](https://docs.sympy.org/1.5.1/modules/tensor/array.html#sympy.tensor.array.permutedims) has been added.

Use this function to save the intermediate conversion into numpy object.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ArunimSamudra** [comment]
I would like to work on this issue.

**Comment by ritzvik** [comment]
Go ahead please!

Regards,
Ritwik

**Comment by sidmttl** [comment]
I would like to work on this issue.

Regards,
Siddharth

**Comment by ritzvik** [comment]
Yes, take a try. I don’t know if it’ll work but it’s worth a try.

Regards,
Ritwik

**Comment by VedantParanjape** [comment]
I would like to work on this issue.

Regards,
Vedant

**Comment by ritzvik** [comment]
Sure thing.

Regards,
Ritwik

**Comment by VedantParanjape** [comment]
@ritzvik What do i pass to indices in permutedims?

**Comment by ritzvik** [comment]
I guess you would have to read the documentation.
Please open a PR with whatever you have done, then we’ll see to the required changes over there.

Regards,
Ritwik

**Comment by atulmangat** [comment]
I would like to work on this issue.

**Comment by ritzvik** [comment]
Go ahead, it’s yours!

Regards,
Ritwik
