### ISSUE TITLE
Improve __str__ and __repr__ messages in Geodesic Module

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#410]
🐞 **Problem**

The geodesic module has very less informative string representation. It should be starting with:

"Geodesic Object ... "

Think about a better message.

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in the comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by nimeshvashistha** [comment]
I want to work on this

**Comment by sagnik-chatterjee** [comment]
Can i contribute to this ?

**Comment by NithyaNN3** [comment]
I'd like to work on this!

**Comment by ritzvik** [comment]
With #458 solved, I believe this issue should be closed. At least, remove the Good first issue tag!

**Comment by JeS24** [comment]
#512 fixes this.
