### ISSUE TITLE
Show inheritance in docs

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#412]
🐞 **Problem**
Currently, in docs, there is no way to know, from where classes have been inherited.

💡 **Possible solutions**

https://github.com/einsteinpy/einsteinpy/blob/c92092ce73787a40e2b7b20dcc7ac3024b6089dc/docs/source/api/symbolic/metric.rst#L4-L7

Add another parameter `show-inheritance`, wherever applicable, throughout EinsteinPy

```
.. automodule:: einsteinpy.symbolic.metric 
     :members:
     :show-inheritance:
```
📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by anjalis2112** [comment]
Hi! Can I work on this?

**Comment by ritzvik** [comment]
All yours :)

Regards,
Ritwik

**Comment by PSY27** [comment]
hi can i work on this ?

**Comment by ritzvik** [comment]
As you can see, it’s taken up! 
Thanks for your interest btw! Find any other open good first issues maybe?

Regards,
Ritwik

**Comment by PSY27** [comment]
ok sure

**Comment by SuyashSalampuria** [comment]
If no one is working on it, I would like to take it up

**Comment by ritzvik** [comment]
> If no one is working on it, I would like to take it up

Yups. Go ahead
