### ISSUE TITLE
Adding requirements in requirements.txt 

### ISSUE THREAD

**Issue by sagnik-chatterjee** [einsteinpy/einsteinpy#414]
🐞 **What bugs you?**

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
Hi @sagnik-chatterjee . Our development model is slightly different. All the requirements are already there in setup.cfg.
