### ISSUE TITLE
Follow PEP8 guidelines in all files

### ISSUE THREAD

**Issue by r0cketr1kky** [einsteinpy/einsteinpy#417]
🐞 **Problem**

Follow PEP8 guidelines in all files of the Einsteinpy project.

🎯 **Goal**

To ensure clean code for better readability and reuse.

💡 **Possible solutions**

Run the code through any PEP8 formatter and correct the changes.  

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by r0cketr1kky** [comment]
Could someone assign me this? @ritzvik

**Comment by shreyasbapat** [comment]
What makes you think we are not following PEP8 ?
