### ISSUE TITLE
Use mocking in specific testing codes

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#423]
🐞 **Problem**
The tests for `__str__` and `__repr__` are done in a pretty weird way in

https://github.com/einsteinpy/einsteinpy/blob/c92092ce73787a40e2b7b20dcc7ac3024b6089dc/src/einsteinpy/tests/test_coordinates/test_coord_transform.py#L137-L156

and

https://github.com/einsteinpy/einsteinpy/blob/c92092ce73787a40e2b7b20dcc7ac3024b6089dc/src/einsteinpy/tests/test_coordinates/test_velocity_transform.py#L134-L155

🎯 **Goal**

Something on the lines of this, is desired

https://github.com/einsteinpy/einsteinpy/blob/c92092ce73787a40e2b7b20dcc7ac3024b6089dc/src/einsteinpy/tests/test_plotting/test_fractal.py#L10-L14

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by sidmttl** [comment]
I will like to work on this issue,
I have started to upgrade test_velocity_transform and test_coord_transform to use mock methods.

**Comment by ritzvik** [comment]
Sure! Please go ahead

Regards,
Ritwik

**Comment by ritzvik** [comment]
Closed via #425
