### ISSUE TITLE
Update Notebooks due to addition of predefined metrics

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#430]
🐞 **Problem**
Now, there are predefined metrics available in symbolic module. Use them in example notebooks

🎯 **Goal**

  - [ ] [Notebook I](https://docs.einsteinpy.org/en/latest/examples/Playing%20with%20Contravariant%20and%20Covariant%20Indices%20in%20Tensors(Symbolic).html) - Replace the deprecated `SchwarzschildMetric`, with that from `predefined` module. 
  - [ ] [Notebook II](https://docs.einsteinpy.org/en/latest/examples/Ricci%20Tensor%20and%20Scalar%20Curvature%20symbolic%20calculation.html) - Use `AntiDeSitter` from `predefined` module, instead of explicitly defining it.

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by nimeshvashistha** [comment]
I'd like to work on this issue
