### ISSUE TITLE
EinsteinTensor.from_metric(metric) fail index out of range

### ISSUE THREAD

**Issue by AncientZygote** [einsteinpy/einsteinpy#436]
Fail with 
C:\ANA\lib\site-packages\sympy\tensor\array\ndim_array.py in _parse_index(self, index)
     65         if isinstance(index, (int, Integer)):
     66             if index >= self._loop_size:
---> 67                 raise ValueError("index out of range")
     68             return index
     69 
when executed 
einst = EinsteinTensor.from_metric(metric)
from your Einstein Tensor calculations using Symbolic module example.
🐞 **Problem**

Trackback from my Jupiter lab session on fail:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-36-8ecd1875ee10> in <module>()
----> 1 einst = EinsteinTensor.from_metric(metric)
      2 #einst.tensor()

C:\ANA\lib\site-packages\einsteinpy\symbolic\einstein.py in from_metric(cls, metric)
     47     def from_metric(cls, metric):
     48         t_ricci = RicciTensor.from_metric(metric)
---> 49         r_scalar = RicciScalar.from_riccitensor(t_ricci, t_ricci.parent_metric)
     50         einstein_tensor = (
     51             t_ricci.tensor() - (1 / 2) * metric.lower_config().tensor() * r_scalar.expr

C:\ANA\lib\site-packages\einsteinpy\symbolic\ricci.py in from_riccitensor(cls, riccitensor, parent_metric)
    203             parent_metric = riccitensor.parent_metric
    204         ricci_scalar = tensorcontraction(riccitensor.tensor(), (0, 1))
--> 205         return cls(ricci_scalar, riccitensor.syms, parent_metric=parent_metric)
    206 
    207     @classmethod

C:\ANA\lib\site-packages\einsteinpy\symbolic\ricci.py in __init__(self, arr, syms, parent_metric)
    172         )
    173         self._order = 0
--> 174         self._expr = self.arr[0]
    175 
    176     @property

C:\ANA\lib\site-packages\sympy\tensor\array\dense_ndim_array.py in __getitem__(self, index)
     65                 return self._array[index]
     66             else:
---> 67                 index = self._parse_index(index)
     68                 return self._array[index]
     69 

C:\ANA\lib\site-packages\sympy\tensor\array\ndim_array.py in _parse_index(self, index)
     65         if isinstance(index, (int, Integer)):
     66             if index >= self._loop_size:
---> 67                 raise ValueError("index out of range")
     68             return index
     69 

ValueError: index out of range

🖥 **Please paste the output of following commands**

I am operating out of an Anaconda environment, but did not use conda to obtain and install your code, einsteinpy-0.2.1-py_1.tar.bz2 (I just decompressed it and placed the relevant folder in:
C:\ANA\Lib\site-packages\einsteinpy
Don't use pip.
I'm using SymPy 1.1.1 so perhaps you are expecting later version (couldn't find any version testing in your software though).

Notes I made on the failure:
n \sympy\tensor\array\dense_ndim_array.py __getitem__(self, index) method of class DenseNDimArray(NDimArray) is invoked with intent of retrieving items from an array. If checks for symbolic index (is not). It chen checks if the index is an instance of tuple and if so if any of its elements is a slice. If not it returns, invoking ndim_array.py method parse_index, where a test for index GTE loop_size fails with "Index ouf of range".

I sucessfuly ran some of your code:
sch = SchwarzschildMetric()
sch.tensor()
and
csfm = ChristoffelSymbols.from_metric(sch_inv)
csfm.tensor()
and
new_csfm = csfm.change_config('lll') 
new_csfm.tensor()

Just ran into trouble in the symbolic module test.

I am hoping this problem will look familiar to you.

**Comment by ritzvik** [comment]
@AncientZygote thanks for reporting this :)
I would highly encourage you to paste the code which caused the problem. Other than that, please ensure that you are using the latest developmental code base on github and not from `pip` as there was some API breaking changes in `sympy`.

Steps to install the latest code-base are provided here : 
https://docs.einsteinpy.org/en/stable/getting_started.html#latest-versions

**Comment by ritzvik** [comment]
@shreyasbapat A lot of the troubles could have been avoided if EPY `0.2.2` had been released :(

**Comment by JeS24** [comment]
I cannot replicate this issue on recent API (`einsteinpy>=0.3`). Closing this.
