### ISSUE TITLE
More usage of pytest xfail

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#440]
Instead of try-except for these type of tests, pytest `xfail` could be used

https://github.com/einsteinpy/einsteinpy/blob/8137212d1488bee1c9d2d4e80d45cc242129adb1/src/einsteinpy/tests/test_symbolic/test_tensor.py#L130-L137

**Comment by atulmangat** [comment]
I would like to work on this issue

**Comment by ganeshtero** [comment]
Hello , i have Marked the test functions to prevent unexpected failure and have done other small  improvements to increase the readability of the code.
Please do check
