### ISSUE TITLE
Introduce "name" parameter in Metric Tensor

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#449]
🐞 **Problem**
Provision of `name` parameter is already there in the base class `BaseRelativityTensor` and now it's time to extend it to `MetricTensor`.

🎯 **Goal**

  - [ ] change `symbolic/metric.py`
  - [ ] Introduce `name` in predefined metrics in `symbolic/predefined`

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Fixes #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by JeS24** [comment]
@ritzvik I would like to take up this issue. Can I work on this?

**Comment by shreyasbapat** [comment]
Sure @JeS24

**Comment by JeS24** [comment]
> Sure @JeS24
@shreyasbapat Will connect on Riot, later today.
