### ISSUE TITLE
Add Tensor name to __str__ and __repr__ in Tensor Class

### ISSUE THREAD

**Issue by JeS24** [einsteinpy/einsteinpy#453]
🐞 **What bugs you?**

Currently, both `str` and `repr`,  in `einsteinpy.symbolic.tensor.py > Tensor`, don't show the Tensor name. As such, there is only one way to check the name, that is by explicitly accessing `tensor.name`.

🎯 **Goal**

Technically, `str` is supposed to be readable and `repr` is supposed to be unambiguous. Outputting the tensor `name` should improve both.

💡 **Possible solutions**

Add `name` to `str` and  `repr`. For example, the output of `str(tensor)` could be something like:
```
Tensor TensorName 
[[...]]
```

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Starninja666** [comment]
Sending pull request soon for this issue.
