### ISSUE TITLE
Implement a mechanism for adding/removing "tags" to/from tensor names, after changes to the tensor

### ISSUE THREAD

**Issue by JeS24** [einsteinpy/einsteinpy#454]
🐞 **What bugs you?**

Every Tensor Object has a `name` parameter, that stores the user-defined (and modifiable) name. After any change is made to the tensor, for example a Lorentz Transform or a Config Change, the name remains unmodified. This may make tracking changes to the tensor difficult for extended calculations.

🎯 **Goal**

A tag added to the Tensor name, after **binary** changes are made to the Tensor to mark the respective changes, would be nice to have. For example, after change_config or lorentz_transformation, tags, like "_cc" or "_lt" can be appended/removed.

💡 **Possible solutions**

Write a helper function for altering `name` conditionally.

Edit `BaseRelativityTensor.lorentz_transform()`.

Edit `change_config()` for all Tensors in `einsteinpy.symbolic`.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by JeS24** [comment]
@ritzvik Should I work on this?

**Comment by ritzvik** [comment]
> @ritzvik Should I work on this?

Looking forward to a PR :)
