### ISSUE TITLE
Import Mismatch Errors in CircleCI Build

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#46]
https://circleci.com/gh/einsteinpy/einsteinpy/75?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

See this!

**Comment by shreyasbapat** [comment]
`--doctest-modules` is the issue.

`pytest --doctest-modules -vv` is converted to `pytest  -vv` to fix it. A hack, but it's fine until we find a solution.

**Comment by shreyasbapat** [comment]
Related to this: https://github.com/pytest-dev/pytest/issues/2042

**Comment by JeS24** [comment]
I guess, [this](https://github.com/pytest-dev/pytest/issues/2042#issuecomment-381309723) and [this](https://github.com/pytest-dev/pytest/issues/539#issuecomment-466197972) are relevant. Also, [this comment](https://github.com/pytest-dev/pytest/issues/2042#issuecomment-429289164). We can perhaps close this issue now. @shreyasbapat

**Comment by shreyasbapat** [comment]
Okay!
