### ISSUE TITLE
Remove "inherited from blah-blah" in docstrings

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#465]
🐞 **Problem**
With #442 , #412 was solved. This means explicitly mentioning where it is inherited from, is not required . For example,

https://github.com/einsteinpy/einsteinpy/blob/0e311bec1be2508a28ebd8a3f8b7b944db997269/src/einsteinpy/symbolic/tensor.py#L204-L208

🎯 **Goal**

Find instances of such docstrings and remove them. This is especially common in `Symbolic` module

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request.
 * Add this in the comments:
 	- `Addresses #<put issue number here>` if you are partially fixing the issue.
 	- `Fixes #<put issue number here>` if you are completely fixing the issue.
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by yauneyz** [comment]
I'll do this one too
