### ISSUE TITLE
Stop shipping tests

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#466]
🐞 **Problem**

From `0.3.0` we can stop shipping tests in the package itself. 

🎯 **Goal**

Put tests outside.

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request.
 * Add this in the comments:
 	- `Addresses #<put issue number here>` if you are partially fixing the issue.
 	- `Fixes #<put issue number here>` if you are completely fixing the issue.
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by anish29292** [comment]
Can I work on this?

**Comment by anish29292** [comment]
@shreyasbapat

**Comment by anish29292** [comment]
@shreyasbapat Could you provide further information on this issue.

**Comment by anish29292** [comment]
@ritzvik Please look into this.
