### ISSUE TITLE
Set up a bot which closes support issues automatically

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#467]
🐞 **Problem**

The issues labeled with `Support` has to be closed when the author/us stop interacting on the issue for 3 weeks.

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request.
 * Add this in the comments:
 	- `Addresses #<put issue number here>` if you are partially fixing the issue.
 	- `Fixes #<put issue number here>` if you are completely fixing the issue.
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by JeS24** [comment]
@shreyasbapat This does precisely, what is wanted here: [probot/no-response]( https://github.com/probot/no-response)

**Comment by shreyasbapat** [comment]
This issue is not for you 😬

**Comment by JeS24** [comment]
@shreyasbapat 😅 Sure, do you want me delete that comment?

**Comment by ritzvik** [comment]
> @shreyasbapat 😅 Sure, do you want me delete that comment?

Let it remain. It may help someone 😀

**Comment by yauneyz** [comment]
It will help me lol. I'm going to do it. Thanks @shreyasbapat

**Comment by shreyasbapat** [comment]
Sure. Let me know if something, some configuration needs to be done from my end
