### ISSUE TITLE
Remove a deprecated module

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#468]
🐞 **Problem**
Completely remove
https://github.com/einsteinpy/einsteinpy/blob/0e311bec1be2508a28ebd8a3f8b7b944db997269/src/einsteinpy/symbolic/vacuum_metrics.py#L7

Take care of removing tests and examples(if present anywhere)

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request.
 * Add this in the comments:
 	- `Addresses #<put issue number here>` if you are partially fixing the issue.
 	- `Fixes #<put issue number here>` if you are completely fixing the issue.
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Gagan-Shenoy** [comment]
Hey if you don't have any objection can I work on this issue.
And also could you briefly explain what exactly I'm supposed to do (I'm new to this).

**Comment by ritzvik** [comment]
> Hey if you don't have any objection can I work on this issue.
> And also could you briefly explain what exactly I'm supposed to do (I'm new to this).

Go ahead with the issue :)

Remove the file altogether, remove the related tests from `tests` folder

**Comment by Gagan-Shenoy** [comment]
sure :)
