### ISSUE TITLE
Group jupyter notebooks by module

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#469]
🐞 **Problem**
Jupyter notebooks are listed in haphazard order
https://github.com/einsteinpy/einsteinpy/blob/0e311bec1be2508a28ebd8a3f8b7b944db997269/docs/source/jupyter.rst#L7-L20

Make different section for different modules. This means 3-4 different toctress in the same file

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request.
 * Add this in the comments:
 	- `Addresses #<put issue number here>` if you are partially fixing the issue.
 	- `Fixes #<put issue number here>` if you are completely fixing the issue.
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ali1810** [comment]
Yes I would like to start working on it ....

**Comment by ritzvik** [comment]
> Yes I would like to start working on it ....

Sure :)

**Comment by Suyog7130** [comment]
I would also like to work on this issue.

**Comment by ritzvik** [comment]
The issue doesn’t have room for two. It’s upto @ali1810 , if he wants to discontinue working on this.

Regards,
Ritwik

**Comment by ali1810** [comment]
yes

**Comment by ritzvik** [comment]
@Suyog7130 You may take this up :)

**Comment by Suyog7130** [comment]
Alright!

**Comment by allardbrain** [comment]
Hey @Suyog7130 are you still working on this issue? I can take it over if you aren't.

**Comment by Suyog7130** [comment]
> Hey @Suyog7130 are you still working on this issue? I can take it over if you aren't.

Hey, sorry I did the work sometime back. Have to merge it with the master.
