### ISSUE TITLE
Remove hypersurface deprecated methods

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#483]
🐞 **Problem**
We are moving to `0.3.0`. It means API can change. Remove the deprecated functions(and related tests, if any)

🎯 **Goal**

The File : https://github.com/einsteinpy/einsteinpy/blob/master/src/einsteinpy/hypersurface/schwarzschildembedding.py

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request.
 * Add this in the comments:
 	- `Addresses #<put issue number here>` if you are partially fixing the issue.
 	- `Fixes #<put issue number here>` if you are completely fixing the issue.
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by allardbrain** [comment]
Hello @ritzvik, I may be able to help with this. Where would I find a list of the functions to be deprecated? I don't see any reference to v0.3.0 in the issues or PRs. Or did you provide the link to that code file because all functions therein are being deprecated?

**Comment by ritzvik** [comment]
https://github.com/einsteinpy/einsteinpy/blob/492b95fe5271ffefe51c67fd456a4a70bcfe1d7c/src/einsteinpy/hypersurface/schwarzschildembedding.py#L179-L189

You would just need to remove these functions. They are to be deprecated, as evident from their docstrings.

Kindly go ahead with the issue :)

**Comment by allardbrain** [comment]
Ah, I missed that! Thanks for pointing me in the right direction. I will take this issue.

**Comment by allardbrain** [comment]
@ritzvik I have submitted a Pull Request for this issue: https://github.com/einsteinpy/einsteinpy/pull/488

Please let me know if you require any changes. Thank you!

Erin
