### ISSUE TITLE
Error handling for `config` variable in Tensor class

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#484]
🐞 **Problem**
`config` variable denotes the contravariance-covariance of the tensor. It's lenrth is supposed to be equal to that the order of the tensor. 

🎯 **Goal**

  - [x] Introduce this error handling into `Tensor` class in `symbolic` module
  - [ ] After fixing this, fix [this](https://github.com/einsteinpy/einsteinpy/blob/30a68526b9cea7b21b3f81c0b89d2619c3e19440/docs/source/examples/Lambdify%20symbolic%20calculation.ipynb) example

💡 **Possible solutions**

  - `config` length should be equal to length of the tuple returned by `arr.shape`

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request.
 * Add this in the comments:
 	- `Addresses #<put issue number here>` if you are partially fixing the issue.
 	- `Fixes #<put issue number here>` if you are completely fixing the issue.
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by allardbrain** [comment]
I've begun working on a PR for this issue.

**Comment by ritzvik** [comment]
> I've begun working on a PR for this issue.

@allardbrain , I didn't see your comment earlier, sorry for that :(
If you want, you could take up the second part of the issue.

**Comment by allardbrain** [comment]
This is just about complete. Working on getting the last failing test to pass.

**Comment by allardbrain** [comment]
Oh no, that's a bummer. For updating the example, is it simply to change `config="l"` to `config="ll"`? Or are more code changes required in the subsequent snippets?

**Comment by allardbrain** [comment]
I submitted #491 for this. Just let me know if more work is required. Thanks.

**Comment by ritzvik** [comment]
Issue fixed with #491 and #490 . Thanks @allardbrain & @bibek22
