### ISSUE TITLE
Contradictory `syms` and `arr` passed to BaseRelativityTensor not being caught

### ISSUE THREAD

**Issue by bibek22** [einsteinpy/einsteinpy#485]
🐞 **Problem**

As mentioned in the title, the mismatch between the `syms`, which also indicates the ~order of the Tensor~ number of spacetime dimensions, and the size of the `arr` during `BaseRelativityTensor` instantiation is going unnoticed.
```python
from sympy.abc import x, y
from sympy import symbols
from einsteinpy.symbolic import BaseRelativityTensor

syms = symbols("t x y z")  
t, x, y, z= syms  
T = BaseRelativityTensor([[x, 1],[0, x+y]], syms, config="l")  
print(T.dims)  
T.tensor()  
```

🎯 **Goal**
Implement a check / error handling of inconsistency in` __init__()`

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
@bibek22 , thanks for opening the issue.

P.S. : The error handling should work for 0th order tensors like `RicciScalar`.

**Comment by bibek22** [comment]
@ritzvik 
> P.S. : The error handling should work for 0th order tensors like `RicciScalar`.

What do you mean by this? Is it enough to make sure it accepts 0 order tensor ?

**Comment by ritzvik** [comment]
> @ritzvik
> 
> > P.S. : The error handling should work for 0th order tensors like `RicciScalar`.
> 
> What do you mean by this? Is it enough to make sure it accepts 0 order tensor ?

0 order tensors are ultimately scalars, but can be inherited from `BaseRelativityTensor` for homogeneity. The note was basically for any contributor who is going to solve the issue :)
