### ISSUE TITLE
Ricci Tensor and problems with summation of two fractions

### ISSUE THREAD

**Issue by manzonis98** [einsteinpy/einsteinpy#493]
🐞 **Problem**
As you can see here in the image below I have an issue with the Ricci tensor.
![Schermata da 2020-04-13 22-55-28](https://user-images.githubusercontent.com/63615231/79160495-27112900-7dda-11ea-8f36-3f51f8b32ae4.png)
All the components should be zero as I'm using the Schwarzshild metric. It's easy to see that the output in the image is correct but the two components are not simplifyed.

It's the same with the evaluation of the Ricci Scalar. It is zero but the output is not simplifyed.
![Schermata da 2020-04-13 23-08-34](https://user-images.githubusercontent.com/63615231/79161471-d5699e00-7ddb-11ea-9eb5-eb039f706b70.png)

It could be solved by typing:
`Ric.simplify()` instead of `Ric.tensor()`.
My question is: is it possible to set the sum as default in `.tensor()` or is it necessary to write the `.simplify()`?

Thanks a lot.

**Comment by ritzvik** [comment]
Hi @manzonis98 , thanks for the issue. 
If you see the docs [here](https://docs.einsteinpy.org/en/latest/api/symbolic/tensor.html#einsteinpy.symbolic.tensor.Tensor.simplify) , on calling `R.simplify()` before calling `R.tensor()`, the tensor contained in the class is automatically simplified and `R.tensor()` returns the simplified version.

However, the current design does not look good to me, and an option of `auto_simplify=True` would be great I think.

**Comment by ritzvik** [comment]
I opened #494 to address this :)
