### ISSUE TITLE
simplify after tensorcontraction in ricci.py

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#494]
🐞 **Problem**
```
>>> from einsteinpy.symbolic import RicciTensor, RicciScalar
>>> from einsteinpy.symbolic.predefined import AntiDeSitter
>>> R = RicciScalar.from_metric(AntiDeSitter())
>>> R.tensor()
((sin(t)**2 - 1)*sinh(chi)**2 - 2*cos(t)**2*sinh(chi)**2)/(cos(t)**2*sinh(chi)**2) + ((sin(t)**2 - 1)*sin(theta)**2*sinh(chi)**2 - 2*sin(theta)**2*cos(t)**2*sinh(chi)**2)/(sin(theta)**2*cos(t)**2*sinh(chi)**2) - 6
>>> R.simplify()
-12
>>> R.tensor()
-12
```

This is happening because after `tensorcontraction` in `from_riccitensor` classmethod, simplification is not taking place.

Similar problem in `RicciTensor` class.

🎯 **Goal**

  - Fix this

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request.
 * Add this in the comments:
 	- `Addresses #<put issue number here>` if you are partially fixing the issue.
 	- `Fixes #<put issue number here>` if you are completely fixing the issue.
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Bhavam** [comment]
Hey @ritzvik I made the necessary changes can you take a look .
Thanks
