### ISSUE TITLE
Divide by Zero for coordinate conversion

### ISSUE THREAD

**Issue by jkodish** [einsteinpy/einsteinpy#500]
I tried the coordinate conversion code listed in the guide and g
ot a division by zero error.
Not sure if this is due to the test code or the program itself.

---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-1-044ac74d7993> in <module>
      7 pos_vec = Cartesian(.265003774 * u.km, -153.000000e-03 * u.km,  0 * u.km)
      8 
----> 9 bl_pos = pos_vec.to_bl(a)
     10 print(bl_pos)
     11 

/srv/conda/envs/notebook/lib/python3.7/site-packages/astropy/units/decorators.py in wrapper(*func_args, **func_kwargs)
    232             # Call the original function with any equivalencies in force.
    233             with add_enabled_equivalencies(self.equivalencies):
--> 234                 return_ = wrapped_function(*func_args, **func_kwargs)
    235             if wrapped_signature.return_annotation not in (inspect.Signature.empty, None):
    236                 return return_.to(wrapped_signature.return_annotation)

/srv/conda/envs/notebook/lib/python3.7/site-packages/einsteinpy/coordinates/core.py in to_bl(self, a)
    131 
    132         """
--> 133         r, theta, phi, a = self.convert_bl(a.si.value)
    134         return BoyerLindquist(r * u.m, theta * u.rad, phi * u.rad, a * u.m)
    135 

/srv/conda/envs/notebook/lib/python3.7/site-packages/einsteinpy/coordinates/conversion.py in convert_bl(self, a)
     46             self.vy_si,
     47             self.vz_si,
---> 48             self._velocities_provided,
     49         )
     50 

/srv/conda/envs/notebook/lib/python3.7/site-packages/einsteinpy/coordinates/utils.py in cartesian_to_bl_fast(x, y, z, a, v_x, v_y, v_z, velocities_provided)
     50     if velocities_provided:
     51         return cartesian_to_bl(x, y, z, a, v_x, v_y, v_z)
---> 52     return cartesian_to_bl_novel(x, y, z, a)
     53 
     54 

ZeroDivisionError: division by zero

**Comment by ritzvik** [comment]
Thanks for opening it.
Please check if the issue is the same as that in #343 and follow the discussion there. If the issue is different, then we would move ahead with fixing this.

**Comment by jkodish** [comment]
I can't tell for sure, but this does somewhat look like the same issue.
