### ISSUE TITLE
Symbolic issue with SchwarzschildMetric

### ISSUE THREAD

**Issue by jkodish** [einsteinpy/einsteinpy#501]
All of this is being done in both the binder and my own install. Both show the same issues.

Tried using this: import sympy
from einsteinpy.symbolic import SchwarzschildMetric, ChristoffelSymbols

m = SchwarzschildMetric()
ch = ChristoffelSymbols.from_metric(m)
print(ch[1,2,:])

Got this ImportError

ImportError                               Traceback (most recent call last)
<ipython-input-4-80b3b76bb78f> in <module>
      1 import sympy
----> 2 from einsteinpy.symbolic import SchwarzschildMetric, ChristoffelSymbols
      3 
      4 m = SchwarzschildMetric()
      5 ch = ChristoffelSymbols.from_metric(m)

ImportError: cannot import name 'SchwarzschildMetric' from 'einsteinpy.symbolic' (/srv/conda/envs/notebook/lib/python3.7/site-packages/einsteinpy/symbolic/__init__.py)

**Comment by ritzvik** [comment]
to import schwarzschild metric, the correct line would be this
`from einsteinpy.symbolic.predefined import SchwarzschildMetric`

**Comment by jkodish** [comment]
Still getting the same thing even with the predefined added.

**Comment by jkodish** [comment]
Found what the guide should have:
Should be like this:
import sympy
from einsteinpy.symbolic import ChristoffelSymbols
from einsteinpy.symbolic.predefined import Schwarzschild
m = Schwarzschild()
ch = ChristoffelSymbols.from_metric(m)
print(ch[1,2,:])

**Comment by jkodish** [comment]
This is the output I'm getting so close..but the a doesn't come through as on the guide
[0, 0, -r*(1 - r_s/r), 0]

If I try this: import sympy
from einsteinpy.symbolic import EinsteinTensor
from einsteinpy.symbolic.predefined import Schwarzschild
m = Schwarzschild()
G1 = EinsteinTensor.from_metric(m)
print(G1.arr)
I get all zeros
import sympy

from einsteinpy.symbolic import EinsteinTensor

from einsteinpy.symbolic.predefined import Schwarzschild

m = Schwarzschild()

G1 = EinsteinTensor.from_metric(m)

print(G1.arr)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

**Comment by ritzvik** [comment]
Einstein Tensor is defined as follows:

![ep](https://user-images.githubusercontent.com/24695764/82552194-493b5b00-9b7f-11ea-883c-0332f8a4e771.png)

So, as Ricci tensor vanishes for schwarzschild, so will Ricci Scalar. The expression would evaluate to zero tensor, as obtained by the code.

**Comment by jkodish** [comment]
Ah yes. That's right

**Comment by jkodish** [comment]
May want to change the guide though.thank you for looking at this

**Comment by ritzvik** [comment]
> though

Where is the discrepancy in guide. It would be helpful if you can indicate. 
BTW, thanks for raising the issue.

**Comment by jkodish** [comment]
1) The section where printing the ChristoffelSymbol component should be: 
import sympy
from einsteinpy.symbolic import ChristoffelSymbols
from einsteinpy.symbolic.predefined import Schwarzschild
m = Schwarzschild()
ch = ChristoffelSymbols.from_metric(m)
print(ch[1,2,:])

Currently it is:
import sympy
from einsteinpy.symbolic import SchwarzschildMetric, ChristoffelSymbols
m = SchwarzschildMetric()
ch = ChristoffelSymbols.from_metric(m)
print(ch[1,2,:])
---------------------------------------------------------------------------------------------------
The code

import sympy
from einsteinpy.symbolic import SchwarzschildMetric, EinsteinTensor

m = SchwarzschildMetric()
G1 = EinsteinTensor.from_metric(m)
print(G1.arr)

works producing all zeros, but the result printed in the user guide is 

    [[a*c**2*(-a + r)/r**4 + a*c**2*(a - r)/r**4, 0, 0, 0], [0, a/(r**2*(a - r)) + a/(r**2*(-a + r)), 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]  unless I'm missing something here
