### ISSUE TITLE
Failure: Maxwell tensor contravariant for natural units

### ISSUE THREAD

**Issue by snewtrino** [einsteinpy/einsteinpy#503]
<!--
<img width="1440" alt="Screen Shot 2020-05-25 at 12 00 20 PM" src="https://user-images.githubusercontent.com/59405744/82834769-51e1a900-9e7f-11ea-85cd-4a7816d4dbe1.png">

🐞When I run a test of the EinsteinPy package, I get one error regarding the Maxwell tensor
 =================================== FAILURES ===================================
_____________ test_maxwell_tensor_contravariant_for_natural_units ______________

    def test_maxwell_tensor_contravariant_for_natural_units():
        #  Theoretical background is required to write extensive tests. Right now only skew-symmetric property is being checked.
        M = 1e22
        r = 5.5
        theta = 2 * np.pi / 5
        Q = 45.0
        a = 0.7
        m = kerrnewman_utils.maxwell_tensor_contravariant(r, theta, a, Q, M, 1.0, 1.0, 1.0)
        for t in range(16):
            i = int(t / 4) % 4
            j = t % 4
>           assert_allclose(0, m[i, j] + m[j, i], rtol=0.0, atol=1e-10)
E           AssertionError: 
E           Not equal to tolerance rtol=0, atol=1e-10
E           
E           Mismatched elements: 1 / 1 (100%)
E           Max absolute difference: 1.
E           Max relative difference: 1.
E            x: array(0)
E            y: array(-1.)

**Comment by shreyasbapat** [comment]
Hi @snewtrino , can you please elaborate the issue?

**Comment by shreyasbapat** [comment]
I see, this isse was also discussed here: https://github.com/einsteinpy/einsteinpy/issues/424#issuecomment-631222991

Are you talking about the same thing?

**Comment by shreyasbapat** [comment]
I am sadly unable to recreate this issue. See https://github.com/einsteinpy/einsteinpy/issues/424#issuecomment-636034214 

Can you try out by disabling numba as I mentioned there? Meanwhile, if you are also using a MacBook, I will ask someone to test this on mac.

**Comment by shreyasbapat** [comment]
I am going to close this because we couldn't recreate the issue on any device. You can still comment if you find any problem.
