### ISSUE TITLE
Mathematical error in `utils.schwarzschild_utils.py`

### ISSUE THREAD

**Issue by JeS24** [einsteinpy/einsteinpy#507]
🐞 **Problem**

In [L76](https://github.com/einsteinpy/einsteinpy/blob/d4f162f3c7b8ab5c87ac7fcdc1488a8f31b68252/src/einsteinpy/utils/schwarzschild_utils.py#L76) in `utils.schwarzschild_utils.py`, the constant, a, has been defined as:
```
a = schwarzschild_radius(mass).value
```
 While this should be: 
```
a = -schwarzschild_radius(mass).value # Note the -ve sign
```

🎯 **Goal**

To fix mathematical inaccuracies in the package.

💡 **Possible solutions**

Check this [link]( http://www.physics.usu.edu/Wheeler/GenRel/Lectures/GRNotesDecSchwarzschildGeodesicsPost.pdf) (from the documentation) and compare with [here](https://en.wikipedia.org/wiki/Schwarzschild_metric#The_Schwarzschild_metric).

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by gravitas21** [comment]
I would like to work on this issue.

**Comment by shreyasbapat** [comment]
Hi @gravitas21 , this issue is for GSOC only. Sorry!

**Comment by gravitas21** [comment]
No worries, was waiting for the coreteam reply before starting work. I would suggest putting up a label on GSOC issues to avoid confusion.  Good day!

**Comment by JeS24** [comment]
In #512, `time_velocity` methods, across `<Metric>_utils` modules, have been [moved to and repackaged into 1 function in `coordinates.utils`](https://github.com/JeS24/einsteinpy/blob/0f90cb36d9f90e51659f3ddf204e6cf0302121c4/src/einsteinpy/coordinates/utils.py#L209-L250), renamed as `v_t()`. This function uses the supplied metric and 3-Velocity, and the expression for spacetime interval: $g_{ab} u^a u ^b = 0 or 1$ (null-like or time-like), to determine the timelike component of 4-Velocity, and hence it bypasses this issue completely.
