### ISSUE TITLE
Use __all__ wherever necessary

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#516]
🐞 **Problem**

We do a lot of `from a import *` type of imports. Its necessary to add `__all__`  everywhere.

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request.
 * Add this in the comments:
 	- `Addresses #<put issue number here>` if you are partially fixing the issue.
 	- `Fixes #<put issue number here>` if you are completely fixing the issue.
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ernesto-tapia** [comment]
Hello, I would like to work on this, I'm starting to get familiarized with the project and where to add the _all_.

**Comment by shreyasbapat** [comment]
Hi @ernesto-tapia , sure. Please go ahead with it. If you feel any difficulty , please ask in the chatroom.

**Comment by hkjain** [comment]
Hi @shreyasbapat , I am new to this project and i would like to know about it and resolve the problem, please guide me on how to begin with it once.
