### ISSUE TITLE
Using numpy.vectorize instead of for loops for a better code

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#52]
https://github.com/einsteinpy/einsteinpy/blob/master/src/einsteinpy/utils/coord_transforms.py#L199-L204
For loop can be replaced by np.vectorize by vectorizing the functions used in the for loop

**Comment by m0hdas** [comment]
I doubt the vectorize method is going to produce a better performance. It's merely put there for convenience - check out at the [docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.vectorize.html) .

**Comment by shreyasbapat** [comment]
Hi @m0hdas ! Thanks for pointing that out! But I think I will still prefer `np.vectorize` for a simple benefit: Better Code at EinsteinPy end! As, at last we are anyways going to `@jit` most of the functions. It will be better if we really get into numpy ecosystem.

**Comment by shreyasbapat** [comment]
And as you pointed it out, I am removing the label!

**Comment by pmk21** [comment]
Is anyone working on this? If not, could I give it a shot?

**Comment by ritzvik** [comment]
> Is anyone working on this? If not, could I give it a shot?

Thanks for your interest. Kindly go ahead with the problem.
Similar snippet is also implemented in another utility file : https://github.com/einsteinpy/einsteinpy/blob/master/src/einsteinpy/utils/bl_coord_transforms.py#L224-L228 .

**Comment by pmk21** [comment]
Yes, working on it. Will create PR soon.
