### ISSUE TITLE
Create custom Error class for coordinate operations

### ISSUE THREAD

**Issue by JeS24** [einsteinpy/einsteinpy#526]
🐞 **What bugs you?**

Since some coordinate operations (conversion, calculating 4-Velocity, scalar product et al) depend on the metric tensor, it is imperative that we have the metric class (specifically these methods: `g_cov_` & `_dg_dx_` or alternatively, `_ch_sym_`) defined in the corresponding coordinates. The issue of new coordinates & metric classes is to be tackled by #525. However, we will not be able to have all metric classes defined in all coordinate systems and in such cases, some operations (basically all 4-Vector operations) will be blocked. In those cases, we should display (a) proper error message(s) to the user. It will be useful to define a custom Error class for the same. Currently, we are using `TypeError` and `NotImplementedError` at corresponding places, but we should consolidate these into a single `CoordinateError` or better-named error class, with (an) easy to follow error message(s).

🎯 **Goal**

To provide clarity around coordinate classes and feasibility of some coordinate operations to the end user.

💡 **Possible solutions**

Add a new Error class to `coordinates.utils`, taking into account the aforementioned use case.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by AidanBlant** [comment]
Hi, I'm interested in taking this on.

**Comment by DhawalKhapre** [comment]
Hi, I would like to work on this issue

**Comment by shreyasbapat** [comment]
Sure, please go ahead :D

**Comment by Aditya7799** [comment]
Hi, I've gone through the docs and am interested in working on this issue. 
The error handling could be implemented in two ways:
1. `Error ` base class and `CoordinateError` child class. 
2. One `Error` class with logic to handle different error codes. 

Please do let me know which way would be preferable.

**Comment by JeS24** [comment]
@Aditya7799 Thanks for showing interest. #1 sounds good to me, but at the moment, let's keep the `BaseError` class simple - only as much is needed.
