### ISSUE TITLE
Trajectory figure not visible in Analysing Earth Example

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#529]
🐞 **Problem**

https://docs.einsteinpy.org/en/latest/examples/Analyzing%20Earth%20using%20EinsteinPy!.html

@shreyasbapat @JeS24

**Comment by JeS24** [comment]
This particular example was removed in the last few commits near the end of GSoC 2020. As for the stable version, the figure is present: https://docs.einsteinpy.org/en/stable/examples/Analysing%20Earth%20using%20EinsteinPy%21.html.
