### ISSUE TITLE
Downloading Jupyter notebooks samples

### ISSUE THREAD

**Issue by maajdl** [einsteinpy/einsteinpy#530]
Hello,

Nice package!
I would like to try some Jupyter notebooks samples.
Is there a way to download some?

Thanks

Michel

**Comment by shreyasbapat** [comment]
Hey Michel, sure, you can go and download the whole package in a zip file from this link: 
https://github.com/einsteinpy/einsteinpy/archive/master.zip

Or if you just want to run the jupyter notebooks, they run well in Binder as well:
https://beta.mybinder.org/v2/gh/einsteinpy/einsteinpy/master?filepath=index.ipynb

Glad that you liked it.
