### ISSUE TITLE
Geodesic.py 0.3.0 does not have Timelike

### ISSUE THREAD

**Issue by nicholasferguson** [einsteinpy/einsteinpy#531]
Need to release a 0.4.0

**Comment by shreyasbapat** [comment]
Hi @nicholasferguson , can you please elaborate on what exactly you are looking for?

**Comment by shreyasbapat** [comment]
As for `0.4.0`, the version is planned after GSoC ends. We will have Null Geodesics as a part of it :D
So, it's probably still a 45 days wait for the next release.

**Comment by shreyasbapat** [comment]
Hey @nicholasferguson . I have closed the issue. But if you have any doubts, you can happily reopen or comment on the same issue.
