### ISSUE TITLE
Definition of symbolic constants

### ISSUE THREAD

**Issue by rdisipio** [einsteinpy/einsteinpy#532]
Hi folks,

🐞 **What bugs you?**

  I want to calculate the Einstein tensor for the Alcubierre "warp drive" metric. The calculation of the metric tensor is rather straightforward and has been presented multiple times, e.g. in "Light Propagation in a Warp Drive Spacetime" by Michael Peter Kinach. 

If I define the following symbols

```
syms = sympy.symbols("t x y z x0 sigma R V")
t, x, y, z, x0, sigma, R, V = syms
r0 = sqrt((x - x0)**2 + y + z)
f = (tanh(sigma*(r0+R)) - tanh(sigma*(r0-R))) / (2*tanh(sigma*R))
```

and then
```
g = sympy.Matrix([[(V**2)*(f**2)-1, -V*f, 0, 0], [-V*f, 1, 0,0], [0,0,1,0], [0,0,0,1]]).tolist()
g = MetricTensor(g, (x,V,R,sigma))
```

It looks like this:

`MetricTensor[[V**2*(-tanh(sigma*(-R + sqrt(y + z + (x - x0)**2))) + tanh(sigma*(R + sqrt(y + z + (x - x0)**2))))**2/(4*tanh(R*sigma)**2) - 1, -V*(-tanh(sigma*(-R + sqrt(y + z + (x - x0)**2))) + tanh(sigma*(R + sqrt(y + z + (x - x0)**2))))/(2*tanh(R*sigma)), 0, 0], [-V*(-tanh(sigma*(-R + sqrt(y + z + (x - x0)**2))) + tanh(sigma*(R + sqrt(y + z + (x - x0)**2))))/(2*tanh(R*sigma)), 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]`

The calculation of the Einstein tensor takes a very long time and I couldn't get the result out yet.

🎯 **Goal**

I wonder if that's due to the fact that some symbols are in fact constants (e.g. sigma and R), but the program doesn't know.

💡 **Possible solutions**

I don't know! Is there a way to define constants, and tell EinsteinPy that e.g. only t, x, y, z represent spacetime variables?

Thanks for any reply!
Riccardo

**Comment by rdisipio** [comment]
Oh, I think I've figured that out. The trick was to define two sets of symbols eg. `t, x, y, z` and others for the constants, then pass the first array to the function that calculates the derivatives.

As a side note, you may want to make this a little bit clearer in the examples (although it appears [here](https://docs.einsteinpy.org/en/stable/examples/Symbolically%20Understanding%20Christoffel%20Symbol%20and%20Riemann%20Curvature%20Tensor%20using%20EinsteinPy.html)) and perhaps add this metric to `einsteinpy.symbolic.predefined` ?

Thanks,
Riccardo

**Comment by shreyasbapat** [comment]
Thanks @rdisipio , I think this can be done. I will create an issue to have this metric in the predefined set. Thanks a lot for the feedback, and glad it worked.

**Comment by shreyasbapat** [comment]
> Oh, I think I've figured that out. The trick was to define two sets of symbols eg. t, x, y, z and others for the constants, then pass the first array to the function that calculates the derivatives.

@JeS24 Can you do it in current pull request only, this should be a minor addition to that

**Comment by JeS24** [comment]
@shreyasbapat On it.

**Comment by shreyasbapat** [comment]
This is fixed. Thanks @rdisipio for the issue :D

**Comment by shreyasbapat** [comment]
The changes however, will appear in the 0.4.0 release later this year. You can use the latest master till then :D
