### ISSUE TITLE
No API docs for Geodesic Module

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#539]
🐞 **Problem**

https://docs.einsteinpy.org/en/latest/api/geodesic.html 
This is mostly empty for some reason. @JeS24 you might have an idea why this was not pushed? 

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request.
 * Add this in the comments:
 	- `Addresses #<put issue number here>` if you are partially fixing the issue.
 	- `Fixes #<put issue number here>` if you are completely fixing the issue.
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ShikhaSuman8601** [comment]
I would like to work on this

**Comment by JeS24** [comment]
@shreyasbapat Weird. Let me take a look.

**Comment by JeS24** [comment]
Fixed in #548.
