### ISSUE TITLE
API docs don't list down all the available modules on it's homepage

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#540]
🐞 **Problem**
https://docs.einsteinpy.org/en/latest/api/index.html 

This leads the users to nowhere! 

We need to have a toctree here!

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request.
 * Add this in the comments:
 	- `Addresses #<put issue number here>` if you are partially fixing the issue.
 	- `Fixes #<put issue number here>` if you are completely fixing the issue.
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ridhiratan** [comment]
I would like to work on this.

**Comment by OptXFinite** [comment]
I would also like to work on this. Looks like the toc tree was there but just hidden, so I will submit a PR shortly with the "hide" option removed
