### ISSUE TITLE
Refine Jupyter Notebooks Page in Docs

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#541]
🐞 **Problem**

https://docs.einsteinpy.org/en/latest/jupyter.html

We need to have more descriptive headings in this. Maybe link those headings to some pages. 
@rishi-s8  You may elaborate if you wish.

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request.
 * Add this in the comments:
 	- `Addresses #<put issue number here>` if you are partially fixing the issue.
 	- `Fixes #<put issue number here>` if you are completely fixing the issue.
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Dhawal-Modi** [comment]
Hi i would like to work on this

**Comment by shreyasbapat** [comment]
Sure, please go ahead!

**Comment by jatincse** [comment]
I would like to work on this

**Comment by shreyasbapat** [comment]
Sure, you can.

**Comment by begeistert** [comment]
Hi, I would like to work on this

**Comment by shreyasbapat** [comment]
Please go ahead

_______________________________________
This email is sent from a smartphone. Please ignore grammatical mistakes
and typographical errors.
_______________________________________

**Comment by godslayer201** [comment]
**Problem**

https://docs.einsteinpy.org/en/latest/jupyter.html

We need to have more descriptive headings in this. Maybe link those headings to some pages.

**Goal**

We should maybe make it more descriptive to use. A small summary or link to relevant article should be a good start
 **Possible solutions**

1.Add description of what the code does.
2.Mention a small summary of the problem we're solving,and how we are solving it.

**Steps to solve the problem**

1.Research and repharse the index.rst file 
2.Update as mentioned above.
  
  * `Addresses #<put issue number here>` if you are partially fixing the issue.
  * `Fixes #<put issue number here>` if you are completely fixing the issue.
* Ask for a review in comments section of pull request
* Celebrate your contribution to this project tada

@shreyasbapat this is my line of thought for enhancement. May I work on this? Please let me know if I should change this approach.

**Comment by rajpratyush** [comment]
is this issue open for work @shreyasbapat @godslayer201

**Comment by JeS24** [comment]
> is this issue open for work @shreyasbapat @godslayer201 

@rajpratyush Yeah. You may work on it.

**Comment by rajpratyush** [comment]
Ok great

**Comment by Supaku9** [comment]
Hi I would like to work on this

**Comment by bhavana-263** [comment]
Is this issue still open for work @shreyasbapat

**Comment by JeS24** [comment]
@bhavana-263 It is. You may work on it.
