### ISSUE TITLE
Add official dev docs for Windows 

### ISSUE THREAD

**Issue by kakirastern** [einsteinpy/einsteinpy#543]
🐞 **What bugs you?**
Currently there are no detailed doc giving instructions as to how to set up a Windows PC for EinsteinPy development work.

🎯 **Goal**
To develop a minimally viable set of instructions to set up Windows PC for EinsteinPy. This will allow users who does not have access to either a Mac or a Linux/Unix machine to contribute to EinsteinPy as well. 

💡 **Possible solutions**
We can use a copy of the Windows VM for testing out the instructions. (https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/)

📋  **Steps to solve the problem**
Try and replicate the instructions for existing setups and re-write documentation. 

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by godslayer201** [comment]
@kakirastern I would like to work on this 

My approach -
1. Concise windows centric doc
2. Include an possible FAQ of all the possible errors that may arise
3. Include relevant gifs of the error behaviour and how to resolve.

**Comment by kakirastern** [comment]
@godslayer201 Thanks for your interest in the issue. You are more than welcome to prepare a PR for it!

**Comment by godslayer201** [comment]
Thank you! Will get started.

**Comment by kakirastern** [comment]
You are welcome! Go for it

**Comment by JeS24** [comment]
@godslayer201 Ping me, if you need to test something out. I mostly use Windows.

Also, [CONTRIBUTING](https://github.com/einsteinpy/einsteinpy/blob/master/CONTRIBUTING.rst) covers all aspects of EPy dev on Windows, except one. `makefile` won't work natively on Windows. While WSL, Cygwin or MinGW can be used, the simplest way to build docs is to use `sphinx-build -b html .\source\ .\build\`. There are ways [to convert `makefile` to `make.bat`](https://pypi.org/project/make-to-batch/), which too would work on Windows. Other than this, all other steps are identical across platforms.

**Comment by godslayer201** [comment]
Yes sure! Let's take this up over IRC? 

I had a couple of doubts of my own as well.

**Comment by JeS24** [comment]
@godslayer201 Sure. We can talk over Matrix.
