### ISSUE TITLE
Addition of Assign-bot

### ISSUE THREAD

**Issue by godslayer201** [einsteinpy/einsteinpy#545]
🐞 **What bugs you?**
We should add an assign bot to automate assigning the issues/PR to willing contributors

🎯 **Goal**
1. Keep track of assigness
2. Increases the organization

💡 **Possible solutions**
1. Addition of assign-bot

📋  **Steps to solve the problem**

 1. It could also happen that someone claims but doesn't work. Need to take care of it for future contributors.
 2.  A tracking mechanism should be set up?

**Comment by JeS24** [comment]
Potentially useful: https://github.com/kentaro-m/auto-assign/
