### ISSUE TITLE
Some of `einsteinpy.symbolic` Jupyter Notebooks are outdated

### ISSUE THREAD

**Issue by JeS24** [einsteinpy/einsteinpy#549]
🐞 **Problem**
As the title suggests, some of the Jupyter Notebooks (stored at `einsteinpy\docs\source\examples\`), containing examples for the `symbolic` module are out of date. Compare these (**_OLD vs NEW_**):

1. https://docs.einsteinpy.org/en/latest/examples/Weyl%20Tensor%20symbolic%20calculation.html
![image](https://user-images.githubusercontent.com/31299799/103639629-a0f2cf00-4f74-11eb-89a4-464f1f015935.png)
![image](https://user-images.githubusercontent.com/31299799/103639617-9b958480-4f74-11eb-8e35-ea1194b71515.png)

2. https://docs.einsteinpy.org/en/latest/examples/Ricci%20Tensor%20and%20Scalar%20Curvature%20symbolic%20calculation.html
![image](https://user-images.githubusercontent.com/31299799/103639670-b8ca5300-4f74-11eb-909e-d51bf63295a1.png)
![image](https://user-images.githubusercontent.com/31299799/103639673-b9fb8000-4f74-11eb-8d0c-41c7b44670f5.png)

3. https://docs.einsteinpy.org/en/latest/examples/Einstein%20Tensor%20symbolic%20calculation.html
![image](https://user-images.githubusercontent.com/31299799/103639692-c67fd880-4f74-11eb-99bc-5ab3f7185b87.png)
![image](https://user-images.githubusercontent.com/31299799/103639707-cd0e5000-4f74-11eb-9fc0-47610e95ae58.png)

(Check other notebooks as well)

The output is the same, except in the old API, mathematical expressions were not completely simplified, while the new API simplifies those, as much as possible.

🎯 **Goal**

To "simplify" the output and make the results in the examples as accurate as they can be.

💡 **Possible solutions**

A simple notebook re-run with the new code would suffice.

📋  **Steps to solve the problem**

 * See [CONTRIBUTING](https://github.com/einsteinpy/einsteinpy/blob/master/CONTRIBUTING.rst#development-environment) to get started with EinsteinPy development.
 * Run the Jupyter Notebooks with `einsteinpy>=0.4` (as on `master`).
 * Add, commit, push your changes
 * Submit a pull request.
 * Add this in the comments:
 	- `Addresses #<put issue number here>` if you are partially fixing the issue.
 	- `Fixes #<put issue number here>` if you are completely fixing the issue.
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by prakashaditya369** [comment]
I would like to work on this issue.
@JeS24 In this issue, I have to check for various examples in the doc and check if the output is outdated or not. If outdated, I need to change it. Am I right?

**Comment by JeS24** [comment]
@prakashaditya369 Yeah, just running the Jupyter Notebooks in `examples/` with `einsteinpy>=0.4.0` would do.
