### ISSUE TITLE
Renaming `master` to `main` has lead to link rot

### ISSUE THREAD

**Issue by JeS24** [einsteinpy/einsteinpy#570]
🐞 **Problem**

We recently renamed the `master` branch to `main` and it has lead to link rot. While GitHub automatically interprets links with  `master` as references to `main`, external sites like Binder do not (See #567).

🎯 **Goal**

To fix link rot.

💡 **Possible solutions**

Replace `master` with `main` for all relevant occurrences, throughout the repo.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes.
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`.
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by prakashaditya369** [comment]
I would like to work on this issue.
I should change all `master` to `main` even for those which Github are inferencing correctly.
And for this I need to look into `.rst` files only, right?

**Comment by JeS24** [comment]
> I should change all `master` to `main` even for those which Github are inferencing correctly.

Correct.

> And for this I need to look into `.rst` files only, right?

Mostly `.rst`, but some instances of `master` may be in some HTML templates and even configuration scripts (Python or otherwise). Just search through the repo.

**Comment by prakashaditya369** [comment]
@JeS24 I search for every possible master in the project. I left the following "master":
- `master` in`.git` and `.github` folder.
- `"master.svg"` in some link in `README.rst`
- `master_doc` in `docs/source/config.py`

Still while building, I am getting this `master` as branch in some html files:
![Screenshot from 2021-01-22 01-16-44](https://user-images.githubusercontent.com/62632865/105404609-2bfbe680-5c50-11eb-830f-4667029cc477.png)
Is it due to some setting in [codecov.io](codecov.io) itself and I should create a pull request or am I missing something?

**Comment by JeS24** [comment]
@prakashaditya369 That is because, there are 10 instances of `master` in `README.rst`:

![image](https://user-images.githubusercontent.com/31299799/105406270-31f2c700-5c52-11eb-895d-b9dea4d0d619.png)

**Comment by prakashaditya369** [comment]
I renamed all of them except master.svg.
The ones I have mentioned above are ones whom I haven't renamed.

**Comment by JeS24** [comment]
@prakashaditya369 `codecov` was using `master` as the default branch. I have changed it to `main`. In any case, you can add `"badge_branch": "main",` to `html_theme_options` in `conf.py` to force `codecov` ([and others](https://alabaster.readthedocs.io/en/latest/customization.html#service-links-and-badges)) to use `main`, while generating the badge(s).


> * `"master.svg"` in some link in `README.rst`

Rename this too.

**Comment by prakashaditya369** [comment]
@JeS24 I am getting this error while compiling.
![Screenshot from 2021-01-22 14-16-32](https://user-images.githubusercontent.com/62632865/105468391-f2ad9000-5cbc-11eb-834b-28ceb9da61fa.png)

The change I have made.
![Screenshot from 2021-01-22 14-16-40](https://user-images.githubusercontent.com/62632865/105468386-f0e3cc80-5cbc-11eb-95c1-c791d9cc0a1b.png)

**Comment by JeS24** [comment]
@prakashaditya369 Set `"badge_branch"` before `"codecov_button"`.

**Comment by prakashaditya369** [comment]
@JeS24 It didn't work.
