### ISSUE TITLE
Update citations

### ISSUE THREAD

**Issue by JeS24** [einsteinpy/einsteinpy#572]
🐞 **Problem**

In PR #548, we have added a new geodesic solver to EinsteinPy, based on [this paper (arXiv)](https://arxiv.org/abs/2010.02237) by Christian and Chan. At the moment, the code cites the arXiv entry, but the paper has been accepted for publication in The Astrophysical Journal (ApJ). As and when the ApJ DOI becomes available, we should update the citation at corresponding places.

🎯 **Goal**

Keeping our citations up to date.

💡 **Possible solutions**

Update the citation, when the ApJ DOI becomes available. Note that currently, we are using [numpydoc reference guidelines](https://numpydoc.readthedocs.io/en/latest/example.html), but ApJ would have its own citation scheme.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request.
 * Add this in the comments:
 	- `Addresses #<put issue number here>` if you are partially fixing the issue.
 	- `Fixes #<put issue number here>` if you are completely fixing the issue.
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by epsilonethan** [comment]
Saw the ApJ publication was released on March 8th. Started updating the references in fantasy.py, utils.py, and dual.py.
