### ISSUE TITLE
Resolve the Einstein Equations

### ISSUE THREAD

**Issue by AfnanAlsaati** [einsteinpy/einsteinpy#589]
Hello!

There is a way to resolve the Einstein equations with EinsteinPy  ?

If we consider that we have a function B(t) in the tensor, and we want to resolve the einstein equations and to determine the function B(t)

**Comment by AfnanAlsaati** [comment]
I tried to resolve :  
So I want  to add up the Einstein tensor with ( the metric tensor * the cosmological constant) to create one tensor, but I have an error : 

""unsupported operand type(s) for +: 'EinsteinTensor' and 'MetricTensor'   ""

Can I have some help please ?

**Comment by shreyasbapat** [comment]
Hi @AfnanAlsaati , can you please post some code snippet that can help recreate the issue?

**Comment by AfnanAlsaati** [comment]
Hi @shreyasbapat, 
I finally resolve my problem. Here the resolution (according to me).  And I also discover that in EinsteinPy there is an Einstein tensor ! '' EinsteinTensor "

![image](https://user-images.githubusercontent.com/83760863/118866538-63b72a00-b8e2-11eb-8a3c-be367d5746fc.png)

**Comment by JeS24** [comment]
Thanks for opening the issue. As you've discovered, you can use [`EinsteinTensor`](https://github.com/einsteinpy/einsteinpy/blob/main/src/einsteinpy/symbolic/einstein.py#L8) to calculate the required terms. You can also use [`sympy.simplify`](https://docs.sympy.org/latest/tutorials/intro-tutorial/simplification.html) to get further simplified expressions (when applicable). There is a short tutorial on calculating the Einstein Tensor available in EinsteinPy [documentation](https://docs.einsteinpy.org/en/latest/examples/Einstein%20Tensor%20symbolic%20calculation.html).
