### ISSUE TITLE
Error with Schwarzchild Metric import

### ISSUE THREAD

**Issue by jasonkodish** [einsteinpy/einsteinpy#599]
ImportError                               Traceback (most recent call last)
Input In [1], in <cell line: 3>()
      1 import numpy as np
----> 3 from einsteinpy.coordinates.utils import four_position, stacked_vec
      4 from einsteinpy.geodesic import Geodesic
      5 from einsteinpy.metric import Schwarzschild

ImportError: cannot import name 'four_position' from 'einsteinpy.coordinates.utils' (/home/cenobyte/gwpy/venv/lib/python3.9/site-packages/einsteinpy/coordinates/utils.py)

There's someone here who posted a similar error in conda, but this doesn't seem to be isolated to any particular environment.

**Comment by JeS24** [comment]
Thanks for opening this issue. This is related to outdated documentation at https://docs.einsteinpy.org/en/latest/user_guide.html, which has now been updated. Please upgrade to `einsteinpy>=0.4.0` (`pip install`) and consult the updated documentation.
