### ISSUE TITLE
 TypeError: got an unexpected keyword argument 'a' in bodies module

### ISSUE THREAD

**Issue by jasonkodish** [einsteinpy/einsteinpy#600]
🐞 **Problem**

 2 Attractor = Body(name="BH", mass = 1.989e30 * u.kg, a = spin_factor)
      3 BL_obj = BoyerLindquistDifferential(50e5 * u.km, np.pi / 2 * u.rad, np.pi * u.rad, 0 * u.km / u.s, 0 * u.rad / u.s, 0 * u.rad / u.s,spin_factor)
      4 Particle = Body(differential = BL_obj, parent = Attractor)

File ~/gwpy/venv/lib/python3.9/site-packages/astropy/units/decorators.py:231, in QuantityInput.__call__.<locals>.wrapper(*func_args, **func_kwargs)
    228 @wraps(wrapped_function)
    229 def wrapper(*func_args, **func_kwargs):
    230     # Bind the arguments to our new function to the signature of the original.
--> 231     bound_args = wrapped_signature.bind(*func_args, **func_kwargs)
    233     # Iterate through the parameters of the original signature
    234     for param in wrapped_signature.parameters.values():
    235         # We do not support variable arguments (*args, **kwargs)

File /usr/lib/python3.9/inspect.py:3045, in Signature.bind(self, *args, **kwargs)
   3040 def bind(self, /, *args, **kwargs):
   3041     """Get a BoundArguments object, that maps the passed `args`
   3042     and `kwargs` to the function's signature.  Raises `TypeError`
   3043     if the passed arguments can not be bound.
   3044     """
-> 3045     return self._bind(args, kwargs)

File /usr/lib/python3.9/inspect.py:3034, in Signature._bind(self, args, kwargs, partial)
   3032         arguments[kwargs_param.name] = kwargs
   3033     else:
-> 3034         raise TypeError(
   3035             'got an unexpected keyword argument {arg!r}'.format(
   3036                 arg=next(iter(kwargs))))
   3038 return self._bound_arguments_cls(self, arguments)

TypeError: got an unexpected keyword argument 'a'

Not sure if it's a weird python spacing issue or something like that. I tried adjusting the spacing but that didn't change the result.

**Comment by JeS24** [comment]
Thanks for opening the issue. This too is related to outdated documentation, which is now fixed in #607.
