### ISSUE TITLE
Clean up the logo for the readme

### ISSUE THREAD

**Issue by D3FaltXD** [einsteinpy/einsteinpy#604]
🐞 **The rough edges and bad color scheme for dark mode**

🎯 **Fix the logol**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by KaranSinghBisht** [comment]
Hey @D3FaltXD after the fix, should I add the logo png in the src folder?

**Comment by D3FaltXD** [comment]
yea sure... will make a pull request with the job done

**Comment by JeS24** [comment]
Ensure that the logo looks good in both light and dark modes.

**Comment by JeS24** [comment]
We need to update this image file for the changes to work everywhere (including the logo in the README) - https://github.com/einsteinpy/blog.einsteinpy.org/blob/master/img/logo.png.
