### ISSUE TITLE
[FR] Improvements to plotting geodesics

### ISSUE THREAD

**Issue by JeS24** [einsteinpy/einsteinpy#610]
🐞 **What bugs you?**

This is a list of general improvements that can be made to the `einsteinpy.plotting.geodesic.*` module:
- [x] Currently, one cannot pass a plot-title to the plot methods in `einsteinpy.plotting.geodesic.*`. This behaviour should be changed. A workaround for now is to directly access the figure or axes object in the `*GeodesicPlotter` instance and set titles that way, like what has been done in the docs [here](https://docs.einsteinpy.org/en/latest/examples/Using%20Geodesics%20%28Back-ends%20%26%20Plotting%29.html). A direct API-based approach is preferable.
- [x] 3D plots can often have "weird" aspect ratios. For instance, check the plots here - https://github.com/einsteinpy/einsteinpy/pull/336. This should be easily fixable by allowing users to select the aspect-mode that they want to view the plot in. For `StaticGeodesicPlotter`, that uses matplotlib, we can use the `set_aspect()` method ([Ref 1](https://matplotlib.org/3.6.0/users/prev_whats_new/whats_new_3.6.0.html#equal-aspect-ratio-for-3d-plots) & [Ref 2](https://stackoverflow.com/a/73749399/11922029)), while for the `InteractiveGeodesicPlotter`, that uses plotly, we can set the `scene_aspectmode` in the layout ([Ref](https://plotly.com/python/3d-axes/#fixed-ratio-axes)).
- [ ] #612 should fix issue 1 and partially address issue 2 above. Wondering, whether we should show different options for aspect or try to equalize the options across the Static & Interactive plotters, since their API is so similar from the user's perspective. Matplotlib's `equal` nomenclature makes more sense than Plotly's `data`. Let's wait till [`matplotlib==3.7` adds more options for the aspect ratios](https://stackoverflow.com/a/73749399/11922029). Then, we can tackle this.
* *More issues might be added*.

🎯 **Goal**

To enhance the geodesic plotting module.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by mshumayl** [comment]
Hi, just letting you know I've started working on the plot title and aspect ratio API improvement. Will send in a PR for review soon. Thanks!

**Comment by JeS24** [comment]
#612 addresses this almost entirely. **Moving the last one to a separate issue and closing this**.
