### ISSUE TITLE
Existing code not working

### ISSUE THREAD

**Issue by Subhadip-Sau** [einsteinpy/einsteinpy#629]
the following code not working 

from einsteinpy.examples import perihelion

**Comment by JeS24** [comment]
@Subhadip-Sau Thanks for opening the issue. Which EinsteinPy version are you using? If you are on version 0.4+, please follow the updated documentation here: https://docs.einsteinpy.org/en/latest/.

**Comment by JeS24** [comment]
Closing now. If there is some other issue, feel free to comment / reopen.
