### ISSUE TITLE
Einsteinpy.rays seems to have some issue

### ISSUE THREAD

**Issue by R-0-n-Y** [einsteinpy/einsteinpy#637]
Hi,
    I was trying to produce the results of a shadow cast by a thin accretion disk. But somehow the einsteinpy.rays is not working. Therefore the Shadow is not getting imported.

I have tried the example problem but it was working.

Best,
Samik

**Comment by JeS24** [comment]
Hi @R-0-n-Y. Can you post the code you were trying, along with the version of `einsteinpy`, you are using? Currently, there is a known issue with `shadows` (#636), but that is not import related.

**Comment by R-0-n-Y** [comment]
import astropy.units as u
from einsteinpy.rays import Shadow


from einsteinpy.plotting import ShadowPlotter
import matplotlib.pyplot as plt

mass = 1.5 * u.kg
fov = 30 * u.km

shadow = Shadow(mass = mass, fov = fov, n_rays=1000)

obj = ShadowPlotter(shadow=shadow, is_line_plot=True)

obj.plot()
obj.show()


obj = ShadowPlotter(shadow=shadow, is_line_plot=False)

obj.plot()
obj.show()

plt.show()


Sorry the error is something else,

Traceback (most recent call last):
  File "/Users/samikmitra/Downloads/Einsteinpy/blackholedisk.py", line 11, in <module>
    shadow = Shadow(mass = mass, fov = fov, n_rays=1000)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/astropy/units/decorators.py", line 313, in wrapper
    return_ = wrapped_function(*func_args, **func_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/einsteinpy/rays/shadow.py", line 29, in __init__
    root = newton(self._root_equation, 0.1, args=(i,))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/scipy/optimize/_zeros_py.py", line 381, in newton
    raise RuntimeError(msg)
RuntimeError: Failed to converge after 50 iterations, value is nan.

**Comment by JeS24** [comment]
I see. This is the same issue as #636. It seems, `scipy` has made some changes to `newton()`. Can you also post the version of scipy that you are using - type `pip show scipy | grep "Version:"` in your terminal?

**Comment by R-0-n-Y** [comment]
python -c "import scipy; print(scipy.__version__)"
1.10.0

**Comment by JeS24** [comment]
That is weird. I do not see this issue in `scipy<=1.11.0`. Can you add the following snippet to the prior code (in your comment [here](https://github.com/einsteinpy/einsteinpy/issues/637#issuecomment-1722482279)) and run it again, just to confirm the version?
```py
import scipy
print(scipy.__version__)
```
Meanwhile, the "failed to converge" problem seems to arise from some change in `scipy>=1.11.0`.

**Comment by JeS24** [comment]
To add to the previous reply, this also means that a temporary fix is to downgrade `scipy` to `1.10.1` - `pip install scipy==1.10.1`, _if that is an option_. Meanwhile, I am checking what changed in their code.

**Comment by R-0-n-Y** [comment]
I find the code is running from the terminal, but when I am running it from vs code or in jupyter notebook it shows the error. I need to understand it.

**Comment by JeS24** [comment]
> I find the code is running from the terminal, but when I am running it from vs code or in jupyter notebook it shows the error. I need to understand it.

I think, your terminal is using the global python environment, which has `scipy==1.10.0` installed, while VS Code & the notebook are likely using a [virtual environment](https://docs.python.org/3/library/venv.html), where a version of `scipy > 1.10.1` is installed. If I recall correctly, VS Code offers to create a new python (virtual) environment, when a notebook is created.

**Comment by R-0-n-Y** [comment]
Okay, I will check that. 

I have another query. I wanted to modify it for other than the Schwarzschild black hole, so can you let me know what I need to do for that?

**Comment by JeS24** [comment]
Schwarzschild BH has certain symmetries, that allow us to write a simple solution for its shadow. `rays.shadow` implements that simple solution and so, it can't be directly modified for other, more complex BH, like spinning BH. However, you can use EinsteinPy's [geodesic solver](https://github.com/einsteinpy/einsteinpy/blob/main/src/einsteinpy/geodesic/geodesic.py) to ray-trace a few null-like geodesics (i.e., path followed by light) and obtain a shadow that way. Unfortunately, we do not have a straightforward built-in API to do that, at the moment.

**Comment by R-0-n-Y** [comment]
Can I not modify the metric? With some other static solution, not the spinning case. But I want to implement the non-rotating case with some other quantum numbers. And if I want to modify the color, labelling or something else, which source file I need to work/change?

**Comment by JeS24** [comment]
The source code for `rays.shadow` is here - https://github.com/einsteinpy/einsteinpy/blob/main/src/einsteinpy/rays/shadow.py. As you can see, it assumes the Schwarzschild metric. However, some of it might still be applicable to other static solutions with similar symmetries.

>  And if I want to modify the color, labelling or something else, which source file I need to work/change?

The plotting is handled by this module (`ShadowPlotter`) - https://github.com/einsteinpy/einsteinpy/blob/main/src/einsteinpy/plotting/rays/shadow.py.

**Comment by JeS24** [comment]
Tracking https://github.com/scipy/scipy/issues/19272.

**Comment by JeS24** [comment]
Fixed via https://github.com/einsteinpy/einsteinpy/commit/48a1a4aefe7257459c23d75731029a3fa295f829.
