### ISSUE TITLE
Use python dataclasses to streamline `bodies.py`

### ISSUE THREAD

**Issue by JeS24** [einsteinpy/einsteinpy#649]
### 🐞 Problem

There is some redundant code in [`bodies.py`](https://github.com/einsteinpy/einsteinpy/blob/main/src/einsteinpy/bodies.py). Use python [`dataclasses`](https://docs.python.org/3/library/dataclasses.html) to remove the redundancies and streamline the code. *Other solutions are also welcome*. See #647 for a bit more discussion.

### 📋Contribution steps
Please consult the [developer docs](https://docs.einsteinpy.org/en/latest/dev_guide.html) to setup your dev environment and get started. Also, feel free to communicate, if you hit a snag. You can do so in our [Gitter](https://gitter.im/EinsteinPy-Project/EinsteinPy) or [Matrix/Element](https://matrix.to/#/#einsteinpy:matrix.org) chat rooms (recommended), or you can also reply here.

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #649`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by VPraharsha03** [comment]
Hi, I'd like to work on this

**Comment by JeS24** [comment]
@VPraharsha03 Sure. Go ahead.

**Comment by BorisHamadej** [comment]
Hello, is this issue open or is it already taken?

**Comment by JeS24** [comment]
@BorisHamadej @VPraharsha03 is working on this issue. Perhaps, look into #630? It has a list of modules that require documentation updates. Work on the documentation of any of those modules will count towards #630.
