### ISSUE TITLE
about the shadows of black hole

### ISSUE THREAD

**Issue by Drsehrish-iftikhar** [einsteinpy/einsteinpy#653]
🐞 **I am trying to plot the shadows of black hole by using the code:
[Shadow cast by a thin emission disk around a Schwarzschild black hole.ipynb - einsteinpy [GitHub] - Visual Studio Code - GitHub](https://github.dev/einsteinpy/einsteinpy/blob/480bc234cba960b409a6c3d2de6339505e1578e6/docs/source/jupyter.rst#numerical-computations)
I am trying to run this code on the jupyter notebook but not getting any plot due to some error related to "shadowplotter, although, 
 I have installed the package einsteinpy-0.2.1"Can anyone please guide me about this issue? **

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request.
 * Add this in the comments:
 	- `Addresses #<put issue number here>` if you are partially fixing the issue.
 	- `Fixes #<put issue number here>` if you are completely fixing the issue.
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by JeS24** [comment]
@Drsehrish-iftikhar `ShadowPlotter` was added in EPy 0.3.0. Can you update on your end using `pip install --upgrade einsteinpy`? That should install v0.4.1 and fix the issue.

**Comment by Drsehrish-iftikhar** [comment]
Dear
Dr. Jyotrimaya Shivottam

Thank you so much for your response. I will try this, and let you know.

Best regards

Sehrish

**Comment by JeS24** [comment]
@Drsehrish-iftikhar I am closing this issue for now. I hope the issue was resolved. If not, please reopen.
