### ISSUE TITLE
Evolve symbolic calculations related to GR as a seperate module within the library

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#70]
🐞 **What bugs you?**
Along with being a library for numerical relativity, the library should support calculation of core GR related quantities in their symbolic form using [Sympy](https://www.sympy.org/). Currently, some symbolic functions reside in `christoffel.py` in `utils`.

🎯 **Goal**
  - Move functions to a separate module and make this a full fledged feature of the library.
  - Add many more useful quantities.
  - Make the library one-stop solution for GR problems.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #70`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
@shreyasbapat add respective labels

**Comment by ritzvik** [comment]
This looks promising :
  - https://github.com/spacetimeengineer/spacetimeengine

**Comment by rishi-s8** [comment]
There’s already an example about some of these aspects in examples of SymPy. 
I think [this](https://github.com/sympy/sympy/blob/master/examples/advanced/relativity.py) would help.

**Comment by Marlin-Na** [comment]
For reference:
1. [GraviPy](https://pypi.org/project/GraviPy/) has implemented several metrics, including Christoffel symbols, Ricci tensor, Riemann tensor, Einstein tensor and Geodesics.
2. [SageManifolds](https://sagemanifolds.obspm.fr/examples.html) in Sage.

**Comment by ritzvik** [comment]
We can close this I think, as very specific symbolic related issue are being opened now.

Way to go @OVSofia
