### ISSUE TITLE
Link to Jupyter Notebooks in Getting Started is old

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#75]
🐞 **Problem**
In https://einsteinpy-project.readthedocs.io/en/latest/getting_started.html#contribute

> Running your first code using the library
Various examples can be found in the **examples** folder.

As we know, the sphinx beautifully generates the jupyter notebooks in documentation. 
We should link it to that.
A very easy fix

🎯 **Goal**
We should focus on consistency in docs.

💡 **Possible solutions**
Just change the link of examples to: https://einsteinpy-project.readthedocs.io/en/latest/jupyter.html

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Manvi07** [comment]
Hi @shreyasbapat :smiley: 
I would like to fix this issue.

**Comment by shreyasbapat** [comment]
Closed #75 in #143
