### ISSUE TITLE
Add badge for "chat on riot"

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#76]
A "chat on riot" badge can be added to readme.rst just like "chat on gitter" badge. 
See https://shields.io/category/chat

riot chat link : https://riot.im/app/#/room/#einsteinpy:matrix.org

**Comment by ritzvik** [comment]
Done!

**Comment by shreyasbapat** [comment]
Not closed until #77 is merged :)

**Comment by ritzvik** [comment]
Finally done! #77 meeged
