### ISSUE TITLE
Badges in Documentation and README don't match

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#78]
🐞 **Problem**
![screenshot from 2019-03-02 01-25-30](https://user-images.githubusercontent.com/24257914/53662905-34c52700-3c8a-11e9-96f1-5a576f573a75.png)
![screenshot from 2019-03-02 01-25-35](https://user-images.githubusercontent.com/24257914/53662906-355dbd80-3c8a-11e9-93c3-8443b450e507.png)

🎯 **Goal**
These two set of badges should match!

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
@hrishi32 You didn't do it properly! Would you ike to give it a try?

**Comment by hrishi32** [comment]
> @hrishi32 You didn't do it properly! Would you like to give it a try?

Done :)
