### ISSUE TITLE
Markdown in Jupyter Notebook not rendering properly in Sphinx Documentation

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#80]
🐞 Markdown in Jupyter Notebook not rendering properly in Sphinx Documentation

![6](https://user-images.githubusercontent.com/24695764/53684896-50bcdd00-3d0b-11e9-854a-125acd324580.PNG)

See https://einsteinpy-project.readthedocs.io/en/latest/examples/Analysing%20Earth%20using%20EinsteinPy!.html

**Comment by shreyasbapat** [comment]
I am not sure about the complexity of the problem. It might be an upstream problem too!

**Comment by shreyasbapat** [comment]
Fixed in https://github.com/einsteinpy/einsteinpy/commit/d3ae5b7ad5fc4b37fe0eefd6cecaec5b72e51002
