### ISSUE TITLE
Add save methods in plotting classes

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#82]
🐞 **Problem**

The plots, as of now can't be saved in png/jpg format 
🎯 **Goal**

💡 **Possible solutions**

Add a `save` method to all the `*GeodesicPlotters`

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by sashank27** [comment]
Hi! @shreyasbapat I would like to work on this!

**Comment by shreyasbapat** [comment]
Sure @sashank27 ! All yours!
