### ISSUE TITLE
Add a 3D Plotting Module

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#9]
Options: plotly, mayavi, mpl_3D

**Comment by shilpi1958** [comment]
Hey,
I would like to try this!

**Comment by shreyasbapat** [comment]
Hi @shilpi1958 :) Go ahead! But I would like to ask you about your proposal. Can you PM me on matrix?

**Comment by shilpi1958** [comment]
sure! check your inbox :)

**Comment by Varunvaruns9** [comment]
I am working on this. @shreyasbapat
