### ISSUE TITLE
EinsteinPy Logo in ReadTheDocs too large (2 MB).

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#90]
🐞 **Problem**
As the logo is too large, it takes a long time to load as well as significant data usage :( . A smaller logo, probably 50-200 KB is feasible.

💡 **Possible solutions**
Supply with a smaller logo, ```docs/source/_static``` and change the logo in ```docs/source/conf.py``` .

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
Issue might me related to #10

**Comment by shreyasbapat** [comment]
Closed in #93
