### ISSUE TITLE
Add proper docstrings in Integrators module

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#91]
🐞 **Problem**
proper docstrings are absent in ```integrator/runge_kutta.py```.

🎯 **Goal**
 - Adding proper docstrings
 - It's important so that API is reflected correctly in ReadTheDocs.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
Closed in #93
